import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/context/LanguageContext";
import { ThemeProvider } from "@/context/ThemeContext";
import { SpotlightProvider } from "@/context/SpotlightContext";
import { AuthProvider } from "@/context/AuthContext";
import { SessionProvider } from "next-auth/react";
import { CursorProvider } from "@/context/CursorContext";
import { CreditsDialogProvider } from "@/components/credits/CreditsDialogProvider";
import {
  Header,
  Footer,
  CookieBanner,
  ScrollToTop,
  ResponsiveLayoutProvider,
} from "@/components/layout";
import ElasticCursor from "@/components/cursors/ElasticCursor";
import FireCursor from "@/components/cursors/FireCursor";
import SpotlightCursor from "@/components/cursors/SpotlightCursor";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

const geistSans = inter;
const geistMono = robotoMono;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body className={`${inter.variable} font-sans antialiased relative`}>
        <SessionProvider>
          <LanguageProvider>
            <ThemeProvider>
              <SpotlightProvider>
                <AuthProvider>
                  <CursorProvider>
                    <CreditsDialogProvider>
                      <ResponsiveLayoutProvider>
                        <Header />
                        <div className="relative z-0">
                          {children}
                        </div>
                        <Footer />
                        <CookieBanner />
                        <ScrollToTop />
                        <ElasticCursor />
                        <FireCursor />
                        <SpotlightCursor />
                      </ResponsiveLayoutProvider>
                    </CreditsDialogProvider>
                  </CursorProvider>
                </AuthProvider>
              </SpotlightProvider>
            </ThemeProvider>
          </LanguageProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
