"use client"
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

// Define available languages
export type Language = 'en' | 'hi' | 'ar' | 'es' | 'fr';

// Define language names for display
export const languageNames = {
  en: 'English',
  hi: 'हिन्दी',
  ar: 'العربية',
  es: 'Español',
  fr: 'Français'
};

// Define language context type
interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Create the context
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Define translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'app.name': 'Drapels',
    'app.tagline': 'Insights Platform',
    
    // Navigation
    'nav.home': 'Home',
    'nav.roadmaps': 'Roadmaps',
    'nav.companies': 'Companies',
    'nav.community': 'Community',
    'nav.tools': 'Tools',
    'nav.more': 'More',
    'nav.login': 'Login',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.settings': 'Settings',
    
    // Tools dropdown
    'tools.aiquiz': 'AI Quiz',
    'tools.interviewprep': 'Interview Prep',
    'tools.emailgenerator': 'Email Generator',
    'tools.dsasheet': 'DSA Sheet',
    
    // Homepage
    'home.hero.title': 'Master Tech Interviews with AI-Powered Tools',
    'home.hero.subtitle': 'The all-in-one platform for technical interview preparation, with AI-powered practice, real-world coding challenges, and career tools.',
    'home.hero.cta.primary': 'Start Practicing Now',
    'home.hero.cta.secondary': 'Explore Features',
    
    // Features Section
    'home.features.ai.title': 'AI-Powered Learning',
    'home.features.ai.description': 'Personalized learning paths powered by AI to help you master any tech skill.',
    'home.features.ai.tools.neuron': 'Neuron DSA Solver',
    'home.features.ai.tools.mock': 'Mock Interview Simulator',
    'home.features.ai.tools.quiz': 'AI Quiz System',
    'home.features.ai.tools.roadmap': 'Roadmap Generator',
    'home.features.practice.title': 'Practice Platform',
    'home.features.practice.description': 'Hands-on coding environment with real-world challenges and projects.',
    'home.features.practice.tools.compiler': 'Online Compiler',
    'home.features.practice.tools.problem': 'DSA Problem Sets',
    'home.features.practice.tools.documentation': 'Documentation Hub',
    'home.features.career.title': 'Career Tools',
    'home.features.career.description': 'Everything you need for your job search, from resume building to interview prep.',
    'home.features.career.tools.company': 'Company Database',
    'home.features.career.tools.resume': 'Resume Builder',
    'home.features.career.tools.email': 'Cold Email Generator',
    'home.features.career.tools.community': 'Community Forums',
    
    // Interactive Section
    'home.interactive.heading': 'Interactive Learning Experience',
    'home.interactive.subtitle': 'Practice with real-world scenarios and get instant feedback',
    'home.interactive.features.codeEditor': 'Code Editor',
    'home.interactive.features.codeEditorDesc': 'Write, run, and test code in multiple languages',
    'home.interactive.features.collaboration': 'Collaboration',
    'home.interactive.features.collaborationDesc': 'Work with peers and mentors in real-time',
    'home.interactive.features.analytics': 'Analytics',
    'home.interactive.features.analyticsDesc': 'Track your progress and identify areas for improvement',
    'home.interactive.features.timeTracking': 'Time Tracking',
    'home.interactive.features.timeTrackingDesc': 'Practice with time constraints to prepare for real interviews',
    'home.interactive.cta.primary': 'Start Learning',
    'home.interactive.cta.secondary': 'View Demo',
    'home.stats.users': 'Active Users',
    'home.stats.companies': 'Company Partners',
    'home.stats.questions': 'Coding Problems',
    'home.stats.successRate': 'Success Rate',
    
    // CTA Section
    'home.cta.heading': 'Ready to ace your next technical interview?',
    'home.cta.subtitle': 'Join thousands of developers who have landed jobs at top tech companies',
    'home.cta.features.one': 'Personalized learning paths',
    'home.cta.features.two': 'AI-powered practice',
    'home.cta.features.three': 'Real interview questions',
    'home.cta.features.four': 'Career guidance',
    'home.cta.primary': 'Get Started for Free',
    'home.cta.primaryLoggedIn': 'Continue Learning',
    'home.cta.secondary': 'Learn More',
    'home.cta.note': 'No credit card required',
    
    // FAQ Section
    'home.faq.title': 'Frequently Asked Questions',
    'home.faq.subtitle': 'Find answers to common questions about our platform',
    'home.faq.howToStart': 'How do I get started?',
    'home.faq.howToStartAnswer': 'Simply create an account, complete your profile, and start exploring our learning paths and practice problems.',
    'home.faq.freeTrial': 'Is there a free trial?',
    'home.faq.freeTrialAnswer': 'Yes, we offer a 7-day free trial with full access to all features. No credit card required.',
    'home.faq.languages': 'What programming languages do you support?',
    'home.faq.languagesAnswer': 'We support all major programming languages including Python, Java, JavaScript, C++, and more.',
    'home.faq.aiLearning': 'How does the AI learning work?',
    'home.faq.aiLearningAnswer': 'Our AI analyzes your performance and adapts the difficulty and content to match your skill level and learning pace.',
    'home.faq.interviewPrep': 'How can this help with interview preparation?',
    'home.faq.interviewPrepAnswer': 'We provide real interview questions, mock interviews, and detailed feedback to help you prepare effectively.',
    'home.faq.contactPrompt': 'Still have questions? Our team is here to help!',
    'home.faq.contactButton': 'Contact Support',
    'home.features.title': 'Powerful Features',
    'home.features.heading': 'Everything You Need to',
    'home.features.heading.highlight': 'Succeed',
    'home.features.subtitle': 'From skill development to landing interviews, we\'ve got you covered',
    'home.features.roadmaps': 'Company-Specific Roadmaps',
    'home.features.roadmaps.desc': 'Get tailored skill development paths for your target companies',
    'home.features.resources': 'Personalised Quiz',
    'home.features.resources.desc': 'Test your knowledge with AI-powered questions',
    'home.features.insights': 'Interview Preparation',
    'home.features.insights.desc': 'Master common interview questions and scenarios',
    'home.features.email': 'AI Email Generator',
    'home.features.email.desc': 'Create personalized cold emails to reach recruiters effectively',
    'home.companies.title': 'Top Tech Companies',
    'home.companies.heading': 'Supported',
    'home.companies.heading.highlight': 'Companies',
    'home.companies.subtitle': 'Get specialized preparation for top tech companies',
    'home.community': 'Community Insights',
    'home.community.desc': 'Connect with peers and industry professionals to gain valuable insights and expand your professional network.',
    'home.cta.final.title': 'Transform Your Career',
    'home.cta.final.heading': 'Ready to Start Your',
    'home.cta.final.heading.highlight': 'Journey',
    'home.cta.final.subtitle': 'Get personalized roadmaps, curated resources, and insider insights to land your dream job.',
    'home.cta.final.button': 'Get Started Now',
    
    // Home page additional translations
    'home.testimonials.title': 'What Our Users Say',
    'home.testimonials.subtitle': 'Success stories from our community',
    'home.testimonials.priya.name': 'Priya Sharma',
    'home.testimonials.priya.role': 'SDE-1 at Amazon',
    'home.testimonials.priya.content': 'Drapels helped me structure my preparation and land my dream job at Amazon. The company-specific roadmaps were game-changing!',
    'home.testimonials.rahul.name': 'Rahul Kumar',
    'home.testimonials.rahul.role': 'Frontend Developer at Flipkart',
    'home.testimonials.rahul.content': 'The cold email generator helped me connect with recruiters. Got 3 interview calls in just 2 weeks!',
    'home.testimonials.ananya.name': 'Ananya Gupta',
    'home.testimonials.ananya.role': 'Backend Developer at Atlassian',
    'home.testimonials.ananya.content': 'Comprehensive insights about company culture and tech stack helped me prepare better for interviews.',
    'home.interactive.realtime.title': 'Real-time Feedback',
    'home.interactive.realtime.desc': 'Get instant feedback on your progress and performance as you work through our interactive exercises and challenges.',
    
    // About Page
    'about.title': 'About Drapels',
    'about.subtitle': 'A startup initiative dedicated to helping students navigate their career paths and land their dream jobs.',
    'about.mission.title': 'Our Mission',
    'about.mission.para1': 'At Drapels, we believe that every student deserves access to clear, structured pathways to their dream careers. Our platform bridges the gap between academic learning and industry requirements by providing company-specific roadmaps, curated resources, and insider insights.',
    'about.mission.para2': 'Founded in 2025, Drapels is a startup initiative by Arihant Jain, Taizun Kaptan, and Aditya, who experienced firsthand the challenges of navigating career paths in the tech industry. Our mission is to democratize access to career preparation resources and make the journey from student to professional more transparent and achievable.',
    'about.founders.title': 'Meet Our Founders',
    'about.founders.arihant.name': 'Arihant Jain',
    'about.founders.arihant.role': 'Web Builder | Startup Cook',
    'about.founders.arihant.bio': 'Pixels, bugs, coffee, and chaos — I ship perfection daily.',
    'about.founders.taizun.name': 'Taizun Kaptan',
    'about.founders.taizun.role': 'AI Developer',
    'about.founders.taizun.bio': 'Teaching machines to think, so I don\'t have to',
    'about.founders.aditya.name': 'Aditya Rajpoot',
    'about.founders.aditya.role': 'Frontend Developer & Marketing Strategist',
    'about.founders.aditya.bio': 'At Drapels, I turned ideas into interfaces, and vision into visibility',
    'about.join.title': 'Join Us on Our Mission',
    'about.join.desc': 'Whether you\'re a student looking to kickstart your career or an industry professional interested in mentoring, we invite you to join our community and be part of our journey to transform career preparation.',
    
    // Community Page
    'community.categories': 'Categories',
    'community.all': 'All Posts',
    'community.trending': 'Trending',
    'community.recent': 'Recent',
    'community.my_posts': 'My Posts',
    'community.saved': 'Saved',
    'community.popular_tags': 'Popular Tags',
    'community.whats_on_your_mind': 'What\'s on your mind?',
    'community.login_to_post': 'Login to create a post...',
    'community.post': 'Post',
    'community.all_posts': 'All Posts',
    'community.write_a_comment': 'Write a comment...',
    'community.no_saved_posts': 'No saved posts yet',
    'community.no_saved_posts_desc': 'Bookmark posts to save them for later',
    'community.upcoming_events': 'Upcoming Events',
    'community.join': 'Join',
    'community.people_to_follow': 'People to Follow',

    
    // Profile
    'profile.greeting': 'Hi',
    'profile.profile': 'Profile',
    'profile.settings': 'Settings',
    'profile.logout': 'Logout',
    
    // Profile Settings
    'profile.settings.title': 'Profile Settings',
    'profile.redirecting': 'Redirecting...',
    'profile.login.required': 'Please log in to access this page.',
    'profile.tabs.profile': 'Profile Settings',
    'profile.tabs.roadmaps': 'Roadmaps',
    'profile.tabs.quizzes': 'Quizzes',
    'profile.tabs.emails': 'Email Analytics',
    'profile.tabs.dsa': 'DSA Progress',
    
    // Stats Cards
    'stats.total.roadmaps': 'Total Roadmaps',
    'stats.all.available': 'All available roadmaps',
    'stats.completed': 'Completed',
    'stats.completion.rate': 'completion rate',
    'stats.in.progress': 'In Progress',
    'stats.currently.working': 'Currently working on',
    'stats.not.started': 'Not Started',
    'stats.yet.to.begin': 'Yet to begin',
    'stats.total.attempted': 'Total Attempted',
    'stats.quizzes.taken': 'Quizzes taken',
    'stats.average.score': 'Average Score',
    'stats.overall.performance': 'Overall performance',
    'stats.perfect.scores': 'Perfect Scores',
    'stats.accuracy': '100% accuracy',
    'stats.success.rate': 'Success Rate',
    'stats.above.score': 'Above 75% score',
    'stats.recent.performance': 'Recent Performance',
    'stats.category.performance': 'Category Performance',
    'stats.attempts': 'attempts',
    'stats.total.generated': 'Total Generated',
    'stats.emails.created': 'Emails created',
    'stats.templates.used': 'Templates Used',
    'stats.unique.templates': 'Unique templates',
    'stats.avg.words': 'Avg. Words/Email',
    'stats.words.per.email': 'Words per email',
    'stats.monthly.generation': 'Monthly Generation',
    'stats.emails.per.month': 'Emails per month',
    'stats.email.types': 'Email Types Distribution',
    'stats.monthly.trend': 'Monthly Generation Trend',
    'stats.problems.solved': 'Problems Solved',
    'stats.of.total': 'of total',
    'stats.current.streak': 'Current Streak',
    'stats.consecutive.days': 'Consecutive days',
    'stats.longest.streak': 'Longest Streak',
    'stats.best.performance': 'Best performance',
    'stats.first.attempt': 'First attempt success',
    'stats.difficulty.progress': 'Difficulty Level Progress',
    'stats.topic.progress': 'Topic-wise Progress',
    'stats.weekly.activity': 'Weekly Activity',
    'stats.less': 'Less',
    'stats.more': 'More',
    'stats.days.mon': 'Mon',
    'stats.days.tue': 'Tue',
    'stats.days.wed': 'Wed',
    'stats.days.thu': 'Thu',
    'stats.days.fri': 'Fri',
    'stats.days.sat': 'Sat',
    'stats.days.sun': 'Sun',
    'stats.problems.solved.count': '{count} problems solved',
    
    // Settings page
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.language.description': 'Select your preferred language',
    'settings.profile': 'Profile',
    'settings.profile.description': 'Manage your profile information',
    'settings.account': 'Account',
    'settings.account.description': 'Manage your account settings',
    'settings.appearance': 'Appearance',
    'settings.appearance.description': 'Customize the appearance of the application',
    'settings.privacy': 'Privacy & Terms',
    'settings.privacy.description': 'Review our privacy policy and terms of service',
    'settings.save': 'Save Changes',
    'settings.cancel': 'Cancel',
    'settings.darkmode': 'Dark Mode',
    'settings.name': 'Name',
    'settings.email': 'Email',
    'settings.photo': 'Profile Photo',
    'settings.photo.change': 'Change Photo',
    'settings.photo.remove': 'Remove Photo',
    'settings.photo.upload': 'Upload Photo',
    'settings.progress': 'Your Progress',
    'settings.progress.description': 'Track your learning progress',
    
    // Footer
    'footer.rights': 'All rights reserved',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.contact': 'Contact Us',
        // Contact Page
        'contact.title': 'Get in Touch',
        'contact.subtitle': 'Have questions about our platform? Want to collaborate? We\'d love to hear from you.',
        'contact.form.title': 'Send us a Message',
        'contact.form.subtitle': 'Fill out the form below and we\'ll get back to you as soon as possible.',
        'contact.form.firstName': 'First Name',
        'contact.form.firstName.placeholder': 'John',
        'contact.form.lastName': 'Last Name',
        'contact.form.lastName.placeholder': 'Doe',
        'contact.form.email': 'Email',
        'contact.form.email.placeholder': 'john@example.com',
        'contact.form.subject': 'Subject',
        'contact.form.subject.placeholder': 'How can we help you?',
        'contact.form.message': 'Message',
        'contact.form.message.placeholder': 'Tell us more about your inquiry...',
        'contact.form.submit': 'Send Message',
        'contact.info.title': 'Contact Information',
        'contact.info.subtitle': 'Reach out to us through any of these channels.',
        'contact.info.email': 'Email',
        'contact.info.email.value': 'support@drapels.com',
        'contact.info.phone': 'Phone',
        'contact.info.phone.value': '+91 99999 99999',
        'contact.info.address': 'Address',
        'contact.info.address.value': 'Indore, MP',
        'contact.faq.title': 'Frequently Asked Questions',
        'contact.faq.started.question': 'How do I get started?',
        'contact.faq.started.answer': 'Sign up for an account and explore our roadmaps to begin your learning journey.',
        'contact.faq.free.question': 'Is the platform free?',
        'contact.faq.free.answer': 'We offer both free and premium features. Check our pricing for more details.',
            'contact.faq.contribute.question': 'Can I contribute content?',
    'contact.faq.contribute.answer': 'Yes! We welcome contributions from the community. Contact us to learn more.',
    
    // AI Quiz Page
    'aiquiz.title': 'AI Quiz',
    'aiquiz.subtitle': 'Test your knowledge with AI-powered questions',
    'aiquiz.features.ai.title': 'AI-Powered Questions',
    'aiquiz.features.ai.desc': 'Smart questions tailored to your target company and role',
    'aiquiz.features.company.title': 'Company-Specific Focus',
    'aiquiz.features.company.desc': 'Questions based on real interview patterns and requirements',
    'aiquiz.features.explanations.title': 'Detailed Explanations',
    'aiquiz.features.explanations.desc': 'Learn from every question with comprehensive explanations',
    'aiquiz.features.feedback.title': 'Instant Feedback',
    'aiquiz.features.feedback.desc': 'Get immediate results and performance insights',
    'aiquiz.form.company': 'Company',
    'aiquiz.form.role': 'Role',
    'aiquiz.form.domain': 'Domain',
    'aiquiz.form.difficulty': 'Difficulty',
    'aiquiz.form.start': 'Start Quiz',
    'aiquiz.form.custom': 'Custom',
    'aiquiz.quiz.question': 'Question',
    'aiquiz.quiz.of': 'of',
    'aiquiz.quiz.submit': 'Submit Answer',
    'aiquiz.quiz.next': 'Next Question',
    'aiquiz.quiz.finish': 'Finish Quiz',
    'aiquiz.results.title': 'Quiz Results',
    'aiquiz.results.score': 'Your Score',
    'aiquiz.results.correct': 'Correct Answers',
    'aiquiz.results.incorrect': 'Incorrect Answers',
    'aiquiz.results.time': 'Time Spent',
    'aiquiz.results.retake': 'Retake Quiz',
    'aiquiz.results.new': 'New Quiz',
    'aiquiz.history.title': 'Quiz History',
    'aiquiz.history.no': 'No quiz history yet',
    'aiquiz.history.start': 'Start your first quiz to see your progress',
    
    // Roadmap Generator Page
    'roadmap.title': 'Learning Roadmap Generator',
    'roadmap.subtitle': 'Create personalized learning paths for your target companies',
    'roadmap.form.title': 'Generate New Roadmap',
    'roadmap.form.company': 'Company',
    'roadmap.form.company.placeholder': 'e.g., Google, Amazon, Microsoft',
    'roadmap.form.role': 'Role',
    'roadmap.form.role.placeholder': 'e.g., Software Engineer, Data Scientist',
    'roadmap.form.experience': 'Experience Level',
    'roadmap.form.experience.beginner': 'Beginner (0-2 years)',
    'roadmap.form.experience.intermediate': 'Intermediate (2-5 years)',
    'roadmap.form.experience.advanced': 'Advanced (5+ years)',
    'roadmap.form.timeframe': 'Timeframe',
    'roadmap.form.timeframe.short': 'Short (1-3 months)',
    'roadmap.form.timeframe.medium': 'Medium (3-6 months)',
    'roadmap.form.timeframe.long': 'Long (6+ months)',
    'roadmap.form.domain': 'Domain',
    'roadmap.form.domain.placeholder': 'e.g., Web Development, Machine Learning',
    'roadmap.form.focus': 'Focus Areas',
    'roadmap.form.focus.placeholder': 'e.g., Frontend, Backend, Full Stack',
    'roadmap.form.skills': 'Current Skills',
    'roadmap.form.skills.placeholder': 'e.g., JavaScript, Python, React',
    'roadmap.form.generate': 'Generate Roadmap',
    'roadmap.form.loading': 'Generating your roadmap...',
    'roadmap.display.title': 'Your Learning Roadmap',
    'roadmap.display.export': 'Export',
    'roadmap.display.share': 'Share',
    'roadmap.display.delete': 'Delete',
    'roadmap.display.continue': 'Continue Learning',
    'roadmap.library.title': 'Roadmap Library',
    'roadmap.library.subtitle': 'Manage and track your learning journeys',
    'roadmap.library.empty.title': 'No roadmaps yet',
    'roadmap.library.empty.subtitle': 'Create your first learning roadmap to get started!',
    'roadmap.library.empty.button': 'Create Your First Roadmap',
    'roadmap.library.recent': 'Recent Roadmaps',
    'roadmap.library.progress': 'Progress',
    'roadmap.library.updated': 'Updated',
    'roadmap.delete.title': 'Are you absolutely sure?',
    'roadmap.delete.description': 'This action cannot be undone. This will permanently delete your roadmap and remove all of its data from our servers.',
    'roadmap.delete.cancel': 'Cancel',
    'roadmap.delete.confirm': 'Delete',
    
    // Email Generator Page
    'email.title': 'AI Email Generator',
    'email.subtitle': 'Create personalized cold emails to reach recruiters effectively',
    'email.form.name': 'Full Name',
    'email.form.role': 'Current Role',
    'email.form.experience': 'Years of Experience',
    'email.form.skills': 'Key Skills (comma separated)',
    'email.form.projects': 'Notable Projects',
    'email.form.portfolio': 'Portfolio Link',
    'email.form.linkedin': 'LinkedIn Profile',
    'email.form.company': 'Target Company',
    'email.form.targetRole': 'Target Role',
    'email.form.recruiter': 'Recruiter Name',
    'email.form.tone': 'Email Tone',
    'email.form.generate': 'Generate Email',
    'email.form.sample': 'Load Sample Data',
    'email.form.clear': 'Clear Form',
    'email.result.copy': 'Copy Email',
    'email.result.download': 'Download',
    'email.result.share': 'Share',
    'email.tone.professional': 'Professional',
    'email.tone.friendly': 'Friendly',
    'email.tone.confident': 'Confident',
    'email.tone.humble': 'Humble',
    
    // Interview Preps Page
    'interview.title': 'Interview Preparation',
    'interview.subtitle': 'Master common interview questions and scenarios',
    'interview.categories.behavioral': 'Behavioral',
    'interview.categories.behavioral.desc': 'Questions about your past experiences and behavior in work situations',
    'interview.categories.technical': 'Technical',
    'interview.categories.technical.desc': 'Technical questions specific to your field',
    'interview.categories.system': 'System Design',
    'interview.categories.system.desc': 'Design scalable systems and architectures',
    'interview.categories.case': 'Case Studies',
    'interview.categories.case.desc': 'Real-world problem-solving scenarios',
    'interview.question.answer': 'Your Answer',
    'interview.question.submit': 'Submit Answer',
    'interview.question.next': 'Next Question',
    'interview.question.show': 'Show Answer',
    'interview.question.hide': 'Hide Answer',
    'interview.question.tips': 'Tips',
    'interview.question.followup': 'Follow-up Questions',
    'interview.progress.completed': 'Completed',
    'interview.progress.total': 'Total',
    'interview.progress.accuracy': 'Accuracy',
    'interview.progress.time': 'Time Spent',
    
    // DSA Sheet Page
    'dsa.title': 'DSA Practice Sheet',
    'dsa.subtitle': 'Master Data Structures and Algorithms with curated problems',
    'dsa.search.placeholder': 'Search problems...',
    'dsa.filters.topic': 'Topic',
    'dsa.filters.company': 'Company',
    'dsa.filters.difficulty': 'Difficulty',
    'dsa.filters.pattern': 'Pattern',
    'dsa.filters.all': 'All',
    'dsa.filters.bookmarked': 'Bookmarked Only',
    'dsa.filters.completed': 'Completed Only',
    'dsa.sort.title': 'Sort by Title',
    'dsa.sort.difficulty': 'Sort by Difficulty',
    'dsa.sort.company': 'Sort by Company',
    'dsa.problem.solve': 'Mark as Solved',
    'dsa.problem.bookmark': 'Bookmark',
    'dsa.problem.leetcode': 'View on LeetCode',
    'dsa.problem.difficulty.easy': 'Easy',
    'dsa.problem.difficulty.medium': 'Medium',
    'dsa.problem.difficulty.hard': 'Hard',
    'dsa.problem.difficulty.expert': 'Expert',
    'dsa.stats.total': 'Total Problems',
    'dsa.stats.solved': 'Solved',
    'dsa.stats.bookmarked': 'Bookmarked',
    'dsa.stats.completion': 'Completion Rate',
    
    // Company Insights Page
    'company.title': 'Company Insights',
    'company.subtitle': 'Get detailed information about roles, hiring processes, and company culture',
    'company.select.title': 'Select Company',
    'company.select.placeholder': 'Select a company',
    'company.overview.title': 'Company Overview',
    'company.overview.industry': 'Industry',
    'company.overview.founded': 'Founded',
    'company.overview.headquarters': 'Headquarters',
    'company.overview.employees': 'Employees',
    'company.overview.revenue': 'Revenue',
    'company.roles.title': 'Popular Roles',
    'company.roles.salary': 'Salary Range',
    'company.roles.experience': 'Experience Required',
    'company.roles.skills': 'Key Skills',
    'company.culture.title': 'Company Culture',
    'company.culture.values': 'Core Values',
    'company.culture.benefits': 'Benefits & Perks',
    'company.culture.workstyle': 'Work Style',
    'company.hiring.title': 'Hiring Process',
    'company.hiring.stages': 'Interview Stages',
    'company.hiring.duration': 'Process Duration',
    'company.hiring.tips': 'Interview Tips',
    'company.tech.title': 'Tech Stack',
    'company.tech.frontend': 'Frontend Technologies',
    'company.tech.backend': 'Backend Technologies',
    'company.tech.infrastructure': 'Infrastructure',
  },
  
  hi: {
    // Common
    'app.name': 'Drapels',
    'app.tagline': 'इनसाइट्स प्लेटफॉर्म',
    
    // Navigation
    'nav.home': 'होम',
    'nav.roadmaps': 'रोडमैप्स',
    'nav.companies': 'कंपनियां',
    'nav.community': 'कम्युनिटी',
    'nav.tools': 'टूल्स',
    'nav.more': 'अधिक',
    'nav.login': 'लॉगिन',
    'nav.about': 'हमारे बारे में',
    'nav.contact': 'संपर्क करें',
    'nav.settings': 'सेटिंग्स',
    
    // Tools dropdown
    'tools.aiquiz': 'AI क्विज़',
    'tools.interviewprep': 'इंटरव्यू तैयारी',
    'tools.emailgenerator': 'ईमेल जनरेटर',
    'tools.dsasheet': 'DSA शीट',
    
    // Homepage
    'home.hero.title.first': 'अपने कौशल को नेविगेट करें।',
    'home.hero.title.second': 'अपनी सपनों की कंपनी में जगह बनाएं।',
    'home.hero.subtitle': 'अपने करियर को छात्र से पेशेवर तक तेजी से आगे बढ़ाने के लिए कंपनी-विशिष्ट रोडमैप, क्यूरेटेड संसाधन और अंदरूनी जानकारी प्राप्त करें।',
    'home.cta.primary': 'कंपनी चुनें → रोडमैप प्राप्त करें',
    'home.cta.secondary': 'कंपनियां एक्सप्लोर करें',
    'home.features.title': 'शक्तिशाली विशेषताएं',
    'home.features.heading': 'सफल होने के लिए आपको जो चाहिए',
    'home.features.heading.highlight': 'सब कुछ',
    'home.features.subtitle': 'कौशल विकास से लेकर इंटरव्यू तक, हमने आपको कवर किया है',
    'home.features.roadmaps': 'कंपनी-विशिष्ट रोडमैप',
    'home.features.roadmaps.desc': 'अपनी लक्षित कंपनियों के लिए अनुकूलित कौशल विकास पथ प्राप्त करें',
    'home.features.resources': 'क्यूरेटेड संसाधन',
    'home.features.resources.desc': 'हैंड-पिक किए गए ट्यूटोरियल, अभ्यास समस्याओं और सीखने की सामग्री तक पहुंच प्राप्त करें',
    'home.features.insights': 'इंटरव्यू तैयारी',
    'home.features.insights.desc': 'आम इंटरव्यू प्रश्नों और परिदृश्यों में महारत हासिल करें',
    'home.features.email': 'AI ईमेल जनरेटर',
    'home.features.email.desc': 'रिक्रूटर्स तक प्रभावी ढंग से पहुंचने के लिए व्यक्तिगत कोल्ड ईमेल बनाएं',
    'home.companies.title': 'टॉप टेक कंपनियां',
    'home.companies.heading': 'समर्थित',
    'home.companies.heading.highlight': 'कंपनियां',
    'home.companies.subtitle': 'टॉप टेक कंपनियों के लिए विशेष तैयारी प्राप्त करें',
    'home.interactive.heading': 'इंटरैक्टिव',
    'home.interactive.heading.rest': 'लर्निंग एक्सपीरियंस',
    'home.interactive.subtitle': 'अपनी सीखने की यात्रा को बढ़ाने के लिए डिज़ाइन किए गए इंटरैक्टिव तत्वों के माध्यम से हमारे प्लेटफॉर्म के साथ जुड़ें',
    'home.community': 'कम्युनिटी इनसाइट्स',
    'home.community.desc': 'मूल्यवान जानकारी प्राप्त करने और अपने पेशेवर नेटवर्क का विस्तार करने के लिए साथियों और उद्योग पेशेवरों से जुड़ें।',
    'home.cta.final.title': 'अपने करियर को बदलें',
    'home.cta.final.heading': 'अपनी यात्रा शुरू करने के लिए',
    'home.cta.final.heading.highlight': 'तैयार हैं',
    'home.cta.final.subtitle': 'अपनी सपनों की नौकरी पाने के लिए व्यक्तिगत रोडमैप, क्यूरेटेड संसाधन और अंदरूनी जानकारी प्राप्त करें।',
    'home.cta.final.button': 'अभी शुरू करें',
    
    // Home page additional translations
    'home.testimonials.title': 'हमारे उपयोगकर्ता क्या कहते हैं',
    'home.testimonials.subtitle': 'हमारे समुदाय की सफलता की कहानियां',
    'home.testimonials.priya.name': 'प्रिया शर्मा',
    'home.testimonials.priya.role': 'Amazon में SDE-1',
    'home.testimonials.priya.content': 'Drapels ने मुझे अपनी तैयारी को संरचित करने और Amazon में अपनी सपनों की नौकरी पाने में मदद की। कंपनी-विशिष्ट रोडमैप्स गेम-चेंजिंग थे!',
    'home.testimonials.rahul.name': 'राहुल कुमार',
    'home.testimonials.rahul.role': 'Flipkart में Frontend Developer',
    'home.testimonials.rahul.content': 'कोल्ड ईमेल जनरेटर ने मुझे रिक्रूटर्स से जुड़ने में मदद की। सिर्फ 2 हफ्तों में 3 इंटरव्यू कॉल मिले!',
    'home.testimonials.ananya.name': 'अनन्या गुप्ता',
    'home.testimonials.ananya.role': 'Atlassian में Backend Developer',
    'home.testimonials.ananya.content': 'कंपनी संस्कृति और टेक स्टैक के बारे में व्यापक जानकारी ने मुझे इंटरव्यू के लिए बेहतर तैयारी करने में मदद की।',
    
    // Roadmap Generator Page Hindi
    'roadmap.title': 'लर्निंग रोडमैप जनरेटर',
    'roadmap.subtitle': 'अपनी लक्षित कंपनियों के लिए व्यक्तिगत सीखने के पथ बनाएं',
    'roadmap.form.title': 'नया रोडमैप जनरेट करें',
    'roadmap.form.company': 'कंपनी',
    'roadmap.form.company.placeholder': 'जैसे, Google, Amazon, Microsoft',
    'roadmap.form.role': 'भूमिका',
    'roadmap.form.role.placeholder': 'जैसे, Software Engineer, Data Scientist',
    'roadmap.form.experience': 'अनुभव स्तर',
    'roadmap.form.experience.beginner': 'शुरुआती (0-2 वर्ष)',
    'roadmap.form.experience.intermediate': 'मध्यम (2-5 वर्ष)',
    'roadmap.form.experience.advanced': 'उन्नत (5+ वर्ष)',
    'roadmap.form.timeframe': 'समय सीमा',
    'roadmap.form.timeframe.short': 'छोटी (1-3 महीने)',
    'roadmap.form.timeframe.medium': 'मध्यम (3-6 महीने)',
    'roadmap.form.timeframe.long': 'लंबी (6+ महीने)',
    'roadmap.form.domain': 'डोमेन',
    'roadmap.form.domain.placeholder': 'जैसे, Web Development, Machine Learning',
    'roadmap.form.focus': 'फोकस क्षेत्र',
    'roadmap.form.focus.placeholder': 'जैसे, Frontend, Backend, Full Stack',
    'roadmap.form.skills': 'वर्तमान कौशल',
    'roadmap.form.skills.placeholder': 'जैसे, JavaScript, Python, React',
    'roadmap.form.generate': 'रोडमैप जनरेट करें',
    'roadmap.form.loading': 'आपका रोडमैप जनरेट हो रहा है...',
    'roadmap.display.title': 'आपका लर्निंग रोडमैप',
    'roadmap.display.export': 'एक्सपोर्ट',
    'roadmap.display.share': 'शेयर',
    'roadmap.display.delete': 'हटाएं',
    'roadmap.display.continue': 'सीखना जारी रखें',
    'roadmap.library.title': 'रोडमैप लाइब्रेरी',
    'roadmap.library.subtitle': 'अपनी सीखने की यात्राओं का प्रबंधन और ट्रैक करें',
    'roadmap.library.empty.title': 'अभी तक कोई रोडमैप नहीं',
    'roadmap.library.empty.subtitle': 'शुरू करने के लिए अपना पहला लर्निंग रोडमैप बनाएं!',
    'roadmap.library.empty.button': 'अपना पहला रोडमैप बनाएं',
    'roadmap.library.recent': 'हाल के रोडमैप्स',
    'roadmap.library.progress': 'प्रगति',
    'roadmap.library.updated': 'अपडेट किया गया',
    'roadmap.delete.title': 'क्या आप पूरी तरह से सुनिश्चित हैं?',
    'roadmap.delete.description': 'इस कार्रवाई को पूर्ववत नहीं किया जा सकता। यह आपके रोडमैप को स्थायी रूप से हटा देगा और उसके सभी डेटा को हमारे सर्वर से हटा देगा।',
    'roadmap.delete.cancel': 'रद्द करें',
    'roadmap.delete.confirm': 'हटाएं',
    'home.interactive.realtime.title': 'रीयल-टाइम फीडबैक',
    'home.interactive.realtime.desc': 'हमारे इंटरैक्टिव अभ्यास और चुनौतियों के माध्यम से काम करते हुए अपनी प्रगति और प्रदर्शन पर तत्काल फीडबैक प्राप्त करें।',
    
    // About Page
    'about.title': 'Drapels के बारे में',
    'about.subtitle': 'एक स्टार्टअप पहल जो छात्रों को उनके करियर पथ को नेविगेट करने और उनकी सपनों की नौकरी पाने में मदद करने के लिए समर्पित है।',
    'about.mission.title': 'हमारा मिशन',
    'about.mission.para1': 'Drapels में, हम मानते हैं कि हर छात्र को अपने सपनों के करियर के लिए स्पष्ट, संरचित मार्गों तक पहुंच का अधिकार है। हमारा प्लेटफॉर्म कंपनी-विशिष्ट रोडमैप, क्यूरेटेड संसाधन और अंदरूनी जानकारी प्रदान करके शैक्षणिक सीखने और उद्योग आवश्यकताओं के बीच की खाई को पाटता है।',
    'about.mission.para2': '2025 में स्थापित, Drapels Arihant Jain, Taizun Kaptan और Aditya द्वारा एक स्टार्टअप पहल है, जिन्होंने टेक उद्योग में करियर पथ को नेविगेट करने की चुनौतियों का सीधा अनुभव किया। हमारा मिशन करियर तैयारी संसाधनों तक पहुंच को लोकतांत्रिक बनाना और छात्र से पेशेवर तक की यात्रा को अधिक पारदर्शी और प्राप्य बनाना है।',
    'about.founders.title': 'हमारे संस्थापकों से मिलें',
    'about.founders.arihant.name': 'अरिहंत जैन',
    'about.founders.arihant.role': 'वेब बिल्डर | स्टार्टअप कुक',
    'about.founders.arihant.bio': 'पिक्सेल, बग, कॉफी और अराजकता — मैं रोज पूर्णता शिप करता हूं।',
    'about.founders.taizun.name': 'तैजुन कप्तान',
    'about.founders.taizun.role': 'AI डेवलपर',
    'about.founders.taizun.bio': 'मशीनों को सोचना सिखा रहा हूं, ताकि मुझे न सोचना पड़े',
    'about.founders.aditya.name': 'आदित्य राजपूत',
    'about.founders.aditya.role': 'फ्रंटएंड डेवलपर और मार्केटिंग स्ट्रैटेजिस्ट',
    'about.founders.aditya.bio': 'Drapels में, मैंने विचारों को इंटरफेस में बदला, और दृष्टि को दृश्यता में',
    'about.join.title': 'हमारे मिशन में शामिल हों',
    'about.join.desc': 'चाहे आप अपना करियर शुरू करने वाले छात्र हों या मेंटरिंग में रुचि रखने वाले उद्योग पेशेवर, हम आपको हमारे समुदाय में शामिल होने और करियर तैयारी को बदलने की हमारी यात्रा का हिस्सा बनने के लिए आमंत्रित करते हैं।',
    
    // Contact Page
    'contact.title': 'संपर्क करें',
    'contact.subtitle': 'हमारे प्लेटफॉर्म के बारे में प्रश्न हैं? सहयोग करना चाहते हैं? हम आपसे सुनना चाहेंगे।',
    'contact.form.title': 'हमें संदेश भेजें',
    'contact.form.subtitle': 'नीचे दिया गया फॉर्म भरें और हम जल्द ही आपसे संपर्क करेंगे।',
    'contact.form.firstName': 'पहला नाम',
    'contact.form.firstName.placeholder': 'जॉन',
    'contact.form.lastName': 'अंतिम नाम',
    'contact.form.lastName.placeholder': 'डो',
    'contact.form.email': 'ईमेल',
    'contact.form.email.placeholder': 'john@example.com',
    'contact.form.subject': 'विषय',
    'contact.form.subject.placeholder': 'हम आपकी कैसे मदद कर सकते हैं?',
    'contact.form.message': 'संदेश',
    'contact.form.message.placeholder': 'अपनी पूछताछ के बारे में हमें और बताएं...',
    'contact.form.submit': 'संदेश भेजें',
    'contact.info.title': 'संपर्क जानकारी',
    'contact.info.subtitle': 'इनमें से किसी भी चैनल के माध्यम से हमसे संपर्क करें।',
    'contact.info.email': 'ईमेल',
    'contact.info.email.value': 'support@drapels.com',
    'contact.info.phone': 'फोन',
    'contact.info.phone.value': '+91 99999 99999',
    'contact.info.address': 'पता',
    'contact.info.address.value': 'इंदौर, एमपी',
    'contact.faq.title': 'अक्सर पूछे जाने वाले प्रश्न',
    'contact.faq.started.question': 'मैं कैसे शुरू करूं?',
    'contact.faq.started.answer': 'एक खाता बनाएं और अपनी सीखने की यात्रा शुरू करने के लिए हमारे रोडमैप्स का अन्वेषण करें।',
    'contact.faq.free.question': 'क्या प्लेटफॉर्म मुफ्त है?',
    'contact.faq.free.answer': 'हम मुफ्त और प्रीमियम दोनों सुविधाएं प्रदान करते हैं। अधिक जानकारी के लिए हमारी कीमतें देखें।',
    'contact.faq.contribute.question': 'क्या मैं सामग्री में योगदान कर सकता हूं?',
    'contact.faq.contribute.answer': 'हाँ! हम समुदाय से योगदान का स्वागत करते हैं। अधिक जानने के लिए हमसे संपर्क करें।',
    
    // AI Quiz Page Hindi
    'aiquiz.title': 'AI क्विज़',
    'aiquiz.subtitle': 'AI-संचालित प्रश्नों के साथ अपना ज्ञान जांचें',
    'aiquiz.features.ai.title': 'AI-संचालित प्रश्न',
    'aiquiz.features.ai.desc': 'आपकी लक्षित कंपनी और भूमिका के लिए अनुकूलित स्मार्ट प्रश्न',
    'aiquiz.features.company.title': 'कंपनी-विशिष्ट फोकस',
    'aiquiz.features.company.desc': 'वास्तविक इंटरव्यू पैटर्न और आवश्यकताओं पर आधारित प्रश्न',
    'aiquiz.features.explanations.title': 'विस्तृत स्पष्टीकरण',
    'aiquiz.features.explanations.desc': 'व्यापक स्पष्टीकरण के साथ हर प्रश्न से सीखें',
    'aiquiz.features.feedback.title': 'तत्काल फीडबैक',
    'aiquiz.features.feedback.desc': 'तत्काल परिणाम और प्रदर्शन अंतर्दृष्टि प्राप्त करें',
    'aiquiz.form.company': 'कंपनी',
    'aiquiz.form.role': 'भूमिका',
    'aiquiz.form.domain': 'डोमेन',
    'aiquiz.form.difficulty': 'कठिनाई',
    'aiquiz.form.start': 'क्विज़ शुरू करें',
    'aiquiz.form.custom': 'कस्टम',
    'aiquiz.quiz.question': 'प्रश्न',
    'aiquiz.quiz.of': 'का',
    'aiquiz.quiz.submit': 'उत्तर सबमिट करें',
    'aiquiz.quiz.next': 'अगला प्रश्न',
    'aiquiz.quiz.finish': 'क्विज़ समाप्त करें',
    'aiquiz.results.title': 'क्विज़ परिणाम',
    'aiquiz.results.score': 'आपका स्कोर',
    'aiquiz.results.correct': 'सही उत्तर',
    'aiquiz.results.incorrect': 'गलत उत्तर',
    'aiquiz.results.time': 'लगाया गया समय',
    'aiquiz.results.retake': 'क्विज़ दोबारा लें',
    'aiquiz.results.new': 'नई क्विज़',
    'aiquiz.history.title': 'क्विज़ इतिहास',
    'aiquiz.history.no': 'अभी तक कोई क्विज़ इतिहास नहीं',
    'aiquiz.history.start': 'अपनी प्रगति देखने के लिए अपनी पहली क्विज़ शुरू करें',
    
    // NotFound Page
    'notfound.title': '404',
    'notfound.subtitle': 'उफ्फ! पेज नहीं मिला',
    'notfound.home': 'होम पर वापस जाएं',
    
    // Auth Page
    'auth.welcome.title': 'वापसी पर स्वागत है!',
    'auth.welcome.subtitle': 'अपनी करियर की महाशक्तियों को अनलॉक करें!',
    'auth.quote': '"महान काम करने का एकमात्र तरीका यह है कि आप जो करते हैं उसे प्यार करें।"',
    'auth.login': 'लॉगिन',
    'auth.register': 'रजिस्टर',
    'auth.or': 'या',
    
    // Auth Components
    'auth.login.email': 'ईमेल',
    'auth.login.password': 'पासवर्ड',
    'auth.login.success': 'लॉगिन सफल! पुनर्निर्देशित किया जा रहा है...',
    'auth.login.failed': 'लॉगिन विफल: ',
    'auth.login.processing': 'प्रोसेसिंग...',
    'auth.login.button': 'लॉगिन',
    'auth.register.name': 'पूरा नाम',
    'auth.register.email': 'ईमेल',
    'auth.register.password': 'पासवर्ड',
    'auth.register.confirmPassword': 'पासवर्ड की पुष्टि करें',
    'auth.register.success': 'पंजीकरण सफल! पुनर्निर्देशित किया जा रहा है...',
    'auth.register.failed': 'पंजीकरण विफल: ',
    'auth.register.processing': 'प्रोसेसिंग...',
    'auth.register.button': 'रजिस्टर',
    'auth.google.button': 'Google के साथ जारी रखें',
    'auth.apple.button': 'Apple के साथ जारी रखें',
    
    // Community Page
    'community.categories': 'श्रेणियां',
    'community.all': 'सभी पोस्ट',
    'community.trending': 'ट्रेंडिंग',
    'community.recent': 'हाल ही के',
    'community.my_posts': 'मेरी पोस्ट',
    'community.saved': 'सहेजे गए',
    'community.popular_tags': 'लोकप्रिय टैग',
    'community.whats_on_your_mind': 'आपके मन में क्या है?',
    'community.login_to_post': 'पोस्ट करने के लिए लॉगिन करें...',
    'community.post': 'पोस्ट करें',
    'community.all_posts': 'सभी पोस्ट',
    'community.write_a_comment': 'एक टिप्पणी लिखें...',
    'community.no_saved_posts': 'अभी तक कोई सहेजी गई पोस्ट नहीं',
    'community.no_saved_posts_desc': 'बाद में देखने के लिए पोस्ट बुकमार्क करें',
    'community.upcoming_events': 'आगामी कार्यक्रम',
    'community.join': 'शामिल हों',
    'community.people_to_follow': 'फॉलो करने के लिए लोग',

    
    // Profile
    'profile.greeting': 'नमस्ते',
    'profile.profile': 'प्रोफाइल',
    'profile.settings': 'सेटिंग्स',
    'profile.logout': 'लॉगआउट',
    
    // Profile Settings
    'profile.settings.title': 'प्रोफाइल सेटिंग्स',
    'profile.redirecting': 'पुनर्निर्देशित किया जा रहा है...',
    'profile.login.required': 'इस पेज को एक्सेस करने के लिए कृपया लॉग इन करें।',
    'profile.tabs.profile': 'प्रोफाइल सेटिंग्स',
    'profile.tabs.roadmaps': 'रोडमैप्स',
    'profile.tabs.quizzes': 'क्विज़',
    'profile.tabs.emails': 'ईमेल एनालिटिक्स',
    'profile.tabs.dsa': 'डीएसए प्रगति',
    
    // Stats Cards
    'stats.total.roadmaps': 'कुल रोडमैप्स',
    'stats.all.available': 'सभी उपलब्ध रोडमैप्स',
    'stats.completed': 'पूर्ण किए गए',
    'stats.completion.rate': 'पूर्णता दर',
    'stats.in.progress': 'प्रगति पर',
    'stats.currently.working': 'वर्तमान में काम कर रहे हैं',
    'stats.not.started': 'शुरू नहीं किया',
    'stats.yet.to.begin': 'अभी तक शुरू नहीं किया',
    'stats.total.attempted': 'कुल प्रयास',
    'stats.quizzes.taken': 'क्विज़ लिए गए',
    'stats.average.score': 'औसत स्कोर',
    'stats.overall.performance': 'समग्र प्रदर्शन',
    'stats.perfect.scores': 'परफेक्ट स्कोर',
    'stats.accuracy': '100% सटीकता',
    'stats.success.rate': 'सफलता दर',
    'stats.above.score': '75% से अधिक स्कोर',
    'stats.recent.performance': 'हालिया प्रदर्शन',
    'stats.category.performance': 'श्रेणी प्रदर्शन',
    'stats.attempts': 'प्रयास',
    'stats.total.generated': 'कुल जनरेट किए गए',
    'stats.emails.created': 'ईमेल बनाए गए',
    'stats.templates.used': 'उपयोग किए गए टेम्पलेट्स',
    'stats.unique.templates': 'अद्वितीय टेम्पलेट्स',
    'stats.avg.words': 'औसत शब्द/ईमेल',
    'stats.words.per.email': 'प्रति ईमेल शब्द',
    'stats.monthly.generation': 'मासिक जनरेशन',
    'stats.emails.per.month': 'प्रति माह ईमेल',
    'stats.email.types': 'ईमेल प्रकार वितरण',
    'stats.monthly.trend': 'मासिक जनरेशन ट्रेंड',
    'stats.problems.solved': 'हल किए गए प्रश्न',
    'stats.of.total': 'कुल का',
    'stats.current.streak': 'वर्तमान स्ट्रीक',
    'stats.consecutive.days': 'लगातार दिन',
    'stats.longest.streak': 'सबसे लंबी स्ट्रीक',
    'stats.best.performance': 'सर्वश्रेष्ठ प्रदर्शन',
    'stats.first.attempt': 'पहले प्रयास में सफलता',
    'stats.difficulty.progress': 'कठिनाई स्तर प्रगति',
    'stats.topic.progress': 'विषय-वार प्रगति',
    'stats.weekly.activity': 'साप्ताहिक गतिविधि',
    'stats.less': 'कम',
    'stats.more': 'अधिक',
    'stats.days.mon': 'सोम',
    'stats.days.tue': 'मंगल',
    'stats.days.wed': 'बुध',
    'stats.days.thu': 'गुरु',
    'stats.days.fri': 'शुक्र',
    'stats.days.sat': 'शनि',
    'stats.days.sun': 'रवि',
    
    // Settings page
    'settings.title': 'सेटिंग्स',
    'settings.language': 'भाषा',
    'settings.language.description': 'अपनी पसंदीदा भाषा चुनें',
    'settings.profile': 'प्रोफाइल',
    'settings.profile.description': 'अपनी प्रोफाइल जानकारी प्रबंधित करें',
    'settings.account': 'अकाउंट',
    'settings.account.description': 'अपने अकाउंट सेटिंग्स प्रबंधित करें',
    'settings.appearance': 'दिखावट',
    'settings.appearance.description': 'एप्लिकेशन की दिखावट को अनुकूलित करें',
    'settings.privacy': 'गोपनीयता और शर्तें',
    'settings.privacy.description': 'हमारी गोपनीयता नीति और सेवा की शर्तों की समीक्षा करें',
    'settings.save': 'परिवर्तन सहेजें',
    'settings.cancel': 'रद्द करें',
    'settings.darkmode': 'डार्क मोड',
    'settings.name': 'नाम',
    'settings.email': 'ईमेल',
    'settings.photo': 'प्रोफाइल फोटो',
    'settings.photo.change': 'फोटो बदलें',
    'settings.photo.remove': 'फोटो हटाएं',
    'settings.photo.upload': 'फोटो अपलोड करें',
    'settings.progress': 'आपकी प्रगति',
    'settings.progress.description': 'अपनी सीखने की प्रगति को ट्रैक करें',
    
    // Footer
    'footer.rights': 'सर्वाधिकार सुरक्षित',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'सेवा की शर्तें',
    'footer.contact': 'हमसे संपर्क करें',
  },
  
  ar: {
    // Common
    'app.name': 'Drapels',
    'app.tagline': 'منصة الرؤى',
    
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.roadmaps': 'خرائط الطريق',
    'nav.companies': 'الشركات',
    'nav.tools': 'الأدوات',
    'nav.more': 'المزيد',
    'nav.login': 'تسجيل الدخول',
    'nav.about': 'من نحن',
    'nav.contact': 'اتصل بنا',
    'nav.settings': 'الإعدادات',
    
    // Tools dropdown
    'tools.aiquiz': 'اختبار الذكاء الاصطناعي',
    'tools.interviewprep': 'التحضير للمقابلة',
    'tools.emailgenerator': 'منشئ البريد الإلكتروني',
    'tools.dsasheet': 'ورقة DSA',
    
    // Profile
    'profile.greeting': 'مرحبا',
    'profile.profile': 'الملف الشخصي',
    'profile.settings': 'الإعدادات',
    'profile.logout': 'تسجيل الخروج',
    
    // Settings page
    'settings.title': 'الإعدادات',
    'settings.language': 'اللغة',
    'settings.language.description': 'اختر لغتك المفضلة',
    'settings.profile': 'الملف الشخصي',
    'settings.profile.description': 'إدارة معلومات ملفك الشخصي',
    'settings.account': 'الحساب',
    'settings.account.description': 'إدارة إعدادات حسابك',
    'settings.appearance': 'المظهر',
    'settings.appearance.description': 'تخصيص مظهر التطبيق',
    'settings.privacy': 'الخصوصية والشروط',
    'settings.privacy.description': 'مراجعة سياسة الخصوصية وشروط الخدمة',
    'settings.save': 'حفظ التغييرات',
    'settings.cancel': 'إلغاء',
    'settings.darkmode': 'الوضع المظلم',
    'settings.name': 'الاسم',
    'settings.email': 'البريد الإلكتروني',
    'settings.photo': 'صورة الملف الشخصي',
    'settings.photo.change': 'تغيير الصورة',
    'settings.photo.remove': 'إزالة الصورة',
    'settings.photo.upload': 'تحميل الصورة',
    'settings.progress': 'تقدمك',
    'settings.progress.description': 'تتبع تقدم التعلم الخاص بك',
    
    // Footer
    'footer.rights': 'جميع الحقوق محفوظة',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.contact': 'اتصل بنا',
    
    // Home page additional translations
    'home.testimonials.title': 'ماذا يقول مستخدمونا',
    'home.testimonials.subtitle': 'قصص النجاح من مجتمعنا',
    'home.testimonials.priya.name': 'بريا شارما',
    'home.testimonials.priya.role': 'SDE-1 في Amazon',
    'home.testimonials.priya.content': 'ساعدني Drapels في تنظيم تحضيري والحصول على وظيفة أحلامي في Amazon. خرائط الطريق المخصصة للشركة كانت تغييراً جذرياً!',
    'home.testimonials.rahul.name': 'راهول كومار',
    'home.testimonials.rahul.role': 'مطور الواجهة الأمامية في Flipkart',
    'home.testimonials.rahul.content': 'ساعدني منشئ البريد الإلكتروني البارد في التواصل مع المجندين. حصلت على 3 مكالمات مقابلة في أسبوعين فقط!',
    'home.testimonials.ananya.name': 'أنانيا جوبتا',
    'home.testimonials.ananya.role': 'مطور الخلفية في Atlassian',
    'home.testimonials.ananya.content': 'ساعدتني الرؤى الشاملة حول ثقافة الشركة ومكدس التكنولوجيا في التحضير بشكل أفضل للمقابلات.',
    'home.interactive.realtime.title': 'التعليقات الفورية',
    'home.interactive.realtime.desc': 'احصل على تعليقات فورية على تقدمك وأدائك أثناء العمل من خلال تماريننا التفاعلية والتحديات.',
    
    // About Page
    'about.title': 'حول Drapels',
    'about.subtitle': 'مبادرة ناشئة مكرسة لمساعدة الطلاب على التنقل في مسارات حياتهم المهنية والحصول على وظائف أحلامهم.',
    'about.mission.title': 'مهمتنا',
    'about.mission.para1': 'في Drapels، نعتقد أن كل طالب يستحق الوصول إلى مسارات واضحة ومنظمة لحياته المهنية الحلم. تربط منصتنا الفجوة بين التعلم الأكاديمي ومتطلبات الصناعة من خلال توفير خرائط طريق مخصصة للشركة وموارد منسقة ورؤى داخلية.',
    'about.mission.para2': 'تأسست في عام 2025، Drapels هي مبادرة ناشئة من Arihant Jain و Taizun Kaptan و Aditya، الذين عانوا مباشرة من تحديات التنقل في مسارات الحياة المهنية في صناعة التكنولوجيا. مهمتنا هي ديمقراطية الوصول إلى موارد التحضير المهني وجعل الرحلة من الطالب إلى المحترف أكثر شفافية وقابلية للتحقيق.',
    'about.founders.title': 'تعرف على مؤسسينا',
    'about.founders.arihant.name': 'أريانت جاين',
    'about.founders.arihant.role': 'باني الويب | طباخ الشركة الناشئة',
    'about.founders.arihant.bio': 'البكسل، الأخطاء، القهوة، والفوضى — أرسل الكمال يومياً.',
    'about.founders.taizun.name': 'تايزون كابتان',
    'about.founders.taizun.role': 'مطور الذكاء الاصطناعي',
    'about.founders.taizun.bio': 'تعليم الآلات للتفكير، حتى لا أضطر إلى ذلك',
    'about.founders.aditya.name': 'أديتيا راجبوت',
    'about.founders.aditya.role': 'مطور الواجهة الأمامية واستراتيجي التسويق',
    'about.founders.aditya.bio': 'في Drapels، حولت الأفكار إلى واجهات، والرؤية إلى وضوح',
    'about.join.title': 'انضم إلينا في مهمتنا',
    'about.join.desc': 'سواء كنت طالباً تتطلع إلى بدء حياتك المهنية أو محترفاً في الصناعة مهتماً بالتوجيه، ندعوك للانضمام إلى مجتمعنا وأن تكون جزءاً من رحلتنا لتحويل التحضير المهني.',
    'contact.title': 'تواصل معنا',
    'contact.subtitle': 'هل لديك أسئلة حول منصتنا؟ تريد التعاون؟ نود أن نسمع منك.',
    'contact.form.title': 'أرسل لنا رسالة',
    'contact.form.subtitle': 'املأ النموذج أدناه وسنعاود الاتصال بك في أقرب وقت ممكن.',
    'contact.form.firstName': 'الاسم الأول',
    'contact.form.firstName.placeholder': 'جون',
    'contact.form.lastName': 'اسم العائلة',
    'contact.form.lastName.placeholder': 'دو',
    'contact.form.email': 'البريد الإلكتروني',
    'contact.form.email.placeholder': 'john@example.com',
    'contact.form.subject': 'الموضوع',
    'contact.form.subject.placeholder': 'كيف يمكننا مساعدتك؟',
    'contact.form.message': 'الرسالة',
    'contact.form.message.placeholder': 'أخبرنا المزيد عن استفسارك...',
    'contact.form.submit': 'إرسال الرسالة',
    'contact.info.title': 'معلومات الاتصال',
    'contact.info.subtitle': 'تواصل معنا من خلال أي من هذه القنوات.',
    'contact.info.email': 'البريد الإلكتروني',
    'contact.info.email.value': 'support@drapels.com',
    'contact.info.phone': 'الهاتف',
    'contact.info.phone.value': '+91 99999 99999',
    'contact.info.address': 'العنوان',
    'contact.info.address.value': 'إندور، ماديا براديش',
    'contact.faq.title': 'الأسئلة الشائعة',
    'contact.faq.started.question': 'كيف أبدأ؟',
    'contact.faq.started.answer': 'سجل حساباً واستكشف خرائط الطريق الخاصة بنا لبدء رحلة التعلم الخاصة بك.',
    'contact.faq.free.question': 'هل المنصة مجانية؟',
    'contact.faq.free.answer': 'نحن نقدم ميزات مجانية ومميزة. تحقق من أسعارنا لمزيد من التفاصيل.',
    'contact.faq.contribute.question': 'هل يمكنني المساهمة في المحتوى؟',
    'contact.faq.contribute.answer': 'نعم! نرحب بالمساهمات من المجتمع. اتصل بنا لمعرفة المزيد.',
    
    // NotFound Page Arabic
    'notfound.title': '404',
    'notfound.subtitle': 'عذراً! الصفحة غير موجودة',
    'notfound.home': 'العودة إلى الصفحة الرئيسية',
    
    // Auth Page Arabic
    'auth.welcome.title': 'مرحباً بعودتك!',
    'auth.welcome.subtitle': 'افتح قوى حياتك المهنية!',
    'auth.quote': '"الطريقة الوحيدة للقيام بعمل عظيم هي أن تحب ما تفعله."',
    'auth.login': 'تسجيل الدخول',
    'auth.register': 'التسجيل',
    'auth.or': 'أو',
    
    // Auth Components Arabic
    'auth.login.email': 'البريد الإلكتروني',
    'auth.login.password': 'كلمة المرور',
    'auth.login.success': 'تم تسجيل الدخول بنجاح! إعادة التوجيه...',
    'auth.login.failed': 'فشل تسجيل الدخول: ',
    'auth.login.processing': 'جاري المعالجة...',
    'auth.login.button': 'تسجيل الدخول',
    'auth.register.name': 'الاسم الكامل',
    'auth.register.email': 'البريد الإلكتروني',
    'auth.register.password': 'كلمة المرور',
    'auth.register.confirmPassword': 'تأكيد كلمة المرور',
    'auth.register.success': 'تم التسجيل بنجاح! إعادة التوجيه...',
    'auth.register.failed': 'فشل التسجيل: ',
    'auth.register.processing': 'جاري المعالجة...',
    'auth.register.button': 'التسجيل',
    'auth.google.button': 'المتابعة مع Google',
    'auth.apple.button': 'المتابعة مع Apple',
    
    // AI Quiz Page Arabic
    'aiquiz.title': 'اختبار الذكاء الاصطناعي',
    'aiquiz.subtitle': 'اختبر معرفتك بأسئلة مدعومة بالذكاء الاصطناعي',
    'aiquiz.features.ai.title': 'أسئلة مدعومة بالذكاء الاصطناعي',
    'aiquiz.features.ai.desc': 'أسئلة ذكية مخصصة لشركتك المستهدفة ودورك',
    'aiquiz.features.company.title': 'تركيز خاص بالشركة',
    'aiquiz.features.company.desc': 'أسئلة مبنية على أنماط المقابلات الحقيقية والمتطلبات',
    'aiquiz.features.explanations.title': 'شروحات مفصلة',
    'aiquiz.features.explanations.desc': 'تعلم من كل سؤال بشروحات شاملة',
    'aiquiz.features.feedback.title': 'تعليقات فورية',
    'aiquiz.features.feedback.desc': 'احصل على نتائج فورية ورؤى حول الأداء',
    'aiquiz.form.company': 'الشركة',
    'aiquiz.form.role': 'الدور',
    'aiquiz.form.domain': 'المجال',
    'aiquiz.form.difficulty': 'الصعوبة',
    'aiquiz.form.start': 'ابدأ الاختبار',
    'aiquiz.form.custom': 'مخصص',
    'aiquiz.quiz.question': 'السؤال',
    'aiquiz.quiz.of': 'من',
    'aiquiz.quiz.submit': 'إرسال الإجابة',
    'aiquiz.quiz.next': 'السؤال التالي',
    'aiquiz.quiz.finish': 'إنهاء الاختبار',
    'aiquiz.results.title': 'نتائج الاختبار',
    'aiquiz.results.score': 'نتيجتك',
    'aiquiz.results.correct': 'الإجابات الصحيحة',
    'aiquiz.results.incorrect': 'الإجابات الخاطئة',
    'aiquiz.results.time': 'الوقت المستغرق',
    'aiquiz.results.retake': 'إعادة الاختبار',
    'aiquiz.results.new': 'اختبار جديد',
    'aiquiz.history.title': 'تاريخ الاختبارات',
    'aiquiz.history.no': 'لا يوجد تاريخ اختبارات بعد',
    'aiquiz.history.start': 'ابدأ اختبارك الأول لرؤية تقدمك',
    
    // Roadmap Generator Page Arabic
    'roadmap.title': 'مولد خطة التعلم',
    'roadmap.subtitle': 'أنشئ مسارات تعلم مخصصة لشركاتك المستهدفة',
    'roadmap.form.title': 'إنشاء خطة جديدة',
    'roadmap.form.company': 'الشركة',
    'roadmap.form.company.placeholder': 'مثل، Google، Amazon، Microsoft',
    'roadmap.form.role': 'الدور',
    'roadmap.form.role.placeholder': 'مثل، مهندس برمجيات، عالم بيانات',
    'roadmap.form.experience': 'مستوى الخبرة',
    'roadmap.form.experience.beginner': 'مبتدئ (0-2 سنة)',
    'roadmap.form.experience.intermediate': 'متوسط (2-5 سنوات)',
    'roadmap.form.experience.advanced': 'متقدم (5+ سنوات)',
    'roadmap.form.goals': 'الأهداف المهنية',
    'roadmap.form.goals.placeholder': 'صف أهدافك المهنية',
    'roadmap.form.timeline': 'الجدول الزمني',
    'roadmap.form.timeline.placeholder': 'مثل، 3 أشهر، 6 أشهر',
    'roadmap.form.generate': 'إنشاء الخطة',
    'roadmap.display.title': 'خطة التعلم الخاصة بك',
    'roadmap.display.phase': 'المرحلة',
    'roadmap.display.weeks': 'أسابيع',
    'roadmap.display.skills': 'المهارات للتعلم',
    'roadmap.display.resources': 'موارد التعلم',
    'roadmap.display.projects': 'مشاريع التدريب',
    'roadmap.display.milestones': 'المعالم',
    'roadmap.actions.save': 'حفظ الخطة',
    'roadmap.actions.share': 'مشاركة',
    'roadmap.actions.download': 'تحميل PDF',
    'roadmap.actions.new': 'إنشاء خطة جديدة',
    
    // Email Generator Page Arabic
    'email.title': 'منشئ البريد الإلكتروني بالذكاء الاصطناعي',
    'email.subtitle': 'أنشئ رسائل بريد إلكتروني باردة احترافية ومخصصة',
    'email.form.title': 'إنشاء بريد إلكتروني جديد',
    'email.form.recipient': 'المستلم',
    'email.form.recipient.placeholder': 'اسم المستلم أو الشركة',
    'email.form.company': 'الشركة',
    'email.form.company.placeholder': 'اسم الشركة المستهدفة',
    'email.form.role': 'الدور المطلوب',
    'email.form.role.placeholder': 'المسمى الوظيفي الذي تتقدم له',
    'email.form.experience': 'الخبرة ذات الصلة',
    'email.form.experience.placeholder': 'صف خبرتك ذات الصلة بالدور',
    'email.form.tone': 'نبرة الرسالة',
    'email.form.tone.formal': 'رسمي',
    'email.form.tone.friendly': 'ودي',
    'email.form.tone.professional': 'مهني',
    'email.form.generate': 'إنشاء البريد الإلكتروني',
    'email.display.title': 'البريد الإلكتروني المُنشأ',
    'email.actions.copy': 'نسخ',
    'email.actions.download': 'تحميل',
    'email.actions.new': 'إنشاء آخر',
    
    // Interview Preps Page Arabic
    'interview.title': 'التحضير للمقابلة',
    'interview.subtitle': 'استعد للمقابلات مع موارد شاملة وممارسة',
    'interview.sections.technical': 'التحضير التقني',
    'interview.sections.behavioral': 'الأسئلة السلوكية',
    'interview.sections.coding': 'تحديات البرمجة',
    'interview.sections.system': 'تصميم النظام',
    'interview.resources.title': 'موارد التحضير',
    'interview.resources.books': 'كتب موصى بها',
    'interview.resources.courses': 'دورات تدريبية',
    'interview.resources.practice': 'مواقع الممارسة',
    'interview.tips.title': 'نصائح المقابلة',
    'interview.tips.technical': 'راجع المفاهيم الأساسية',
    'interview.tips.behavioral': 'جهز قصص STAR',
    'interview.tips.coding': 'تمرن على حل المشاكل',
    'interview.tips.system': 'ادرس أنماط التصميم',
    
    // DSA Sheet Page Arabic
    'dsa.title': 'ورقة DSA',
    'dsa.subtitle': 'قائمة شاملة لمشاكل هياكل البيانات والخوارزميات',
    'dsa.categories.arrays': 'المصفوفات',
    'dsa.categories.strings': 'النصوص',
    'dsa.categories.linkedlists': 'القوائم المرتبطة',
    'dsa.categories.trees': 'الأشجار',
    'dsa.categories.graphs': 'الرسوم البيانية',
    'dsa.categories.dynamic': 'البرمجة الديناميكية',
    'dsa.categories.greedy': 'الخوارزميات الجشعة',
    'dsa.difficulty.easy': 'سهل',
    'dsa.difficulty.hard': 'صعب',
    'dsa.actions.solve': 'حل',
    'dsa.actions.practice': 'تمرن',
    'dsa.actions.review': 'راجع',
    
    // Company Insights Page Arabic
    'company.title': 'رؤى الشركة',
    'company.subtitle': 'اكتشف ثقافة الشركة والتقنيات والمتطلبات',
    'company.select.title': 'اختر الشركة',
    'company.select.placeholder': 'اختر شركة',
    'company.overview.title': 'نظرة عامة',
    'company.overview.description': 'وصف الشركة والثقافة',
    'company.tech.title': 'التقنيات المستخدمة',
    'company.tech.frontend': 'الواجهة الأمامية',
    'company.tech.backend': 'الخلفية',
    'company.tech.database': 'قاعدة البيانات',
    'company.tech.infrastructure': 'البنية التحتية',
    'company.culture.title': 'ثقافة الشركة',
    'company.culture.values': 'القيم',
    'company.culture.benefits': 'المزايا',
    'company.culture.workstyle': 'أسلوب العمل',
    'company.hiring.title': 'عملية المقابلة',
    'company.hiring.stages': 'مراحل المقابلة',
    'company.hiring.duration': 'مدة العملية',
    'company.hiring.tips': 'نصائح المقابلة',
  },
  
  es: {
    // Common
    'app.name': 'Drapels',
    'app.tagline': 'Plataforma de Insights',
    
    // Navigation
    'nav.home': 'Inicio',
    'nav.roadmaps': 'Hojas de Ruta',
    'nav.companies': 'Empresas',
    'nav.tools': 'Herramientas',
    'nav.more': 'Más',
    'nav.login': 'Iniciar Sesión',
    'nav.about': 'Acerca de',
    'nav.contact': 'Contacto',
    'nav.settings': 'Configuración',
    
    // Tools dropdown
    'tools.aiquiz': 'Quiz de IA',
    'tools.interviewprep': 'Preparación para Entrevistas',
    'tools.emailgenerator': 'Generador de Correos',
    'tools.dsasheet': 'Hoja DSA',
    
    // Profile
    'profile.greeting': 'Hola',
    'profile.profile': 'Perfil',
    'profile.settings': 'Configuración',
    'profile.logout': 'Cerrar Sesión',
    
    // Settings page
    'settings.title': 'Configuración',
    'settings.language': 'Idioma',
    'settings.language.description': 'Selecciona tu idioma preferido',
    'settings.profile': 'Perfil',
    'settings.profile.description': 'Administra tu información de perfil',
    'settings.account': 'Cuenta',
    'settings.account.description': 'Administra la configuración de tu cuenta',
    'settings.appearance': 'Apariencia',
    'settings.appearance.description': 'Personaliza la apariencia de la aplicación',
    'settings.privacy': 'Privacidad y Términos',
    'settings.privacy.description': 'Revisa nuestra política de privacidad y términos de servicio',
    'settings.save': 'Guardar Cambios',
    'settings.cancel': 'Cancelar',
    'settings.darkmode': 'Modo Oscuro',
    'settings.name': 'Nombre',
    'settings.email': 'Correo Electrónico',
    'settings.photo': 'Foto de Perfil',
    'settings.photo.change': 'Cambiar Foto',
    'settings.photo.remove': 'Eliminar Foto',
    'settings.photo.upload': 'Subir Foto',
    'settings.progress': 'Tu Progreso',
    'settings.progress.description': 'Sigue tu progreso de aprendizaje',
    
    // Footer
    'footer.rights': 'Todos los derechos reservados',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.contact': 'Contáctanos',
    
    // Home page additional translations
    'home.testimonials.title': 'Lo que dicen nuestros usuarios',
    'home.testimonials.subtitle': 'Historias de éxito de nuestra comunidad',
    'home.testimonials.priya.name': 'Priya Sharma',
    'home.testimonials.priya.role': 'SDE-1 en Amazon',
    'home.testimonials.priya.content': '¡Drapels me ayudó a estructurar mi preparación y conseguir mi trabajo soñado en Amazon. ¡Las hojas de ruta específicas de la empresa fueron revolucionarias!',
    'home.testimonials.rahul.name': 'Rahul Kumar',
    'home.testimonials.rahul.role': 'Desarrollador Frontend en Flipkart',
    'home.testimonials.rahul.content': 'El generador de correos fríos me ayudó a conectar con reclutadores. ¡Obtuve 3 llamadas de entrevista en solo 2 semanas!',
    'home.testimonials.ananya.name': 'Ananya Gupta',
    'home.testimonials.ananya.role': 'Desarrollador Backend en Atlassian',
    'home.testimonials.ananya.content': 'Las perspectivas integrales sobre la cultura de la empresa y la pila tecnológica me ayudaron a prepararme mejor para las entrevistas.',
    'home.interactive.realtime.title': 'Retroalimentación en Tiempo Real',
    'home.interactive.realtime.desc': 'Obtén retroalimentación instantánea sobre tu progreso y rendimiento mientras trabajas a través de nuestros ejercicios y desafíos interactivos.',
    
    // About Page
    'about.title': 'Acerca de Drapels',
    'about.subtitle': 'Una iniciativa de startup dedicada a ayudar a los estudiantes a navegar sus caminos profesionales y conseguir sus trabajos soñados.',
    'about.mission.title': 'Nuestra Misión',
    'about.mission.para1': 'En Drapels, creemos que cada estudiante merece acceso a caminos claros y estructurados hacia sus carreras soñadas. Nuestra plataforma conecta la brecha entre el aprendizaje académico y los requisitos de la industria proporcionando hojas de ruta específicas de la empresa, recursos curados y perspectivas internas.',
    'about.mission.para2': 'Fundada en 2025, Drapels es una iniciativa de startup por Arihant Jain, Taizun Kaptan y Aditya, quienes experimentaron de primera mano los desafíos de navegar caminos profesionales en la industria tecnológica. Nuestra misión es democratizar el acceso a recursos de preparación profesional y hacer el viaje del estudiante al profesional más transparente y alcanzable.',
    'about.founders.title': 'Conoce a Nuestros Fundadores',
    'about.founders.arihant.name': 'Arihant Jain',
    'about.founders.arihant.role': 'Constructor Web | Cocinero de Startup',
    'about.founders.arihant.bio': 'Píxeles, errores, café y caos — envío perfección diariamente.',
    'about.founders.taizun.name': 'Taizun Kaptan',
    'about.founders.taizun.role': 'Desarrollador de IA',
    'about.founders.taizun.bio': 'Enseñando a las máquinas a pensar, para que yo no tenga que hacerlo',
    'about.founders.aditya.name': 'Aditya Rajpoot',
    'about.founders.aditya.role': 'Desarrollador Frontend y Estratega de Marketing',
    'about.founders.aditya.bio': 'En Drapels, convertí ideas en interfaces, y visión en visibilidad',
    'about.join.title': 'Únete a Nuestra Misión',
    'about.join.desc': 'Ya seas un estudiante buscando impulsar tu carrera o un profesional de la industria interesado en mentoría, te invitamos a unirte a nuestra comunidad y ser parte de nuestro viaje para transformar la preparación profesional.',
        // Contact Page Spanish
        'contact.title': 'Ponte en Contacto',
        'contact.subtitle': '¿Tienes preguntas sobre nuestra plataforma? ¿Quieres colaborar? Nos encantaría saber de ti.',
        'contact.form.title': 'Envíanos un Mensaje',
        'contact.form.subtitle': 'Completa el formulario de abajo y te responderemos lo antes posible.',
        'contact.form.firstName': 'Nombre',
        'contact.form.firstName.placeholder': 'Juan',
        'contact.form.lastName': 'Apellido',
        'contact.form.lastName.placeholder': 'Pérez',
        'contact.form.email': 'Correo Electrónico',
        'contact.form.email.placeholder': 'juan@ejemplo.com',
        'contact.form.subject': 'Asunto',
        'contact.form.subject.placeholder': '¿Cómo podemos ayudarte?',
        'contact.form.message': 'Mensaje',
        'contact.form.message.placeholder': 'Cuéntanos más sobre tu consulta...',
        'contact.form.submit': 'Enviar Mensaje',
        'contact.info.title': 'Información de Contacto',
        'contact.info.subtitle': 'Ponte en contacto con nosotros a través de cualquiera de estos canales.',
        'contact.info.email': 'Correo Electrónico',
        'contact.info.email.value': 'support@drapels.com',
        'contact.info.phone': 'Teléfono',
        'contact.info.phone.value': '+91 99999 99999',
        'contact.info.address': 'Dirección',
        'contact.info.address.value': 'Indore, MP',
        'contact.faq.title': 'Preguntas Frecuentes',
        'contact.faq.started.question': '¿Cómo empiezo?',
        'contact.faq.started.answer': 'Regístrate para una cuenta y explora nuestras hojas de ruta para comenzar tu viaje de aprendizaje.',
        'contact.faq.free.question': '¿La plataforma es gratuita?',
        'contact.faq.free.answer': 'Ofrecemos características gratuitas y premium. Consulta nuestros precios para más detalles.',
        'contact.faq.contribute.question': '¿Puedo contribuir contenido?',
        'contact.faq.contribute.answer': '¡Sí! Damos la bienvenida a las contribuciones de la comunidad. Contáctanos para saber más.',
        
        // NotFound Page Spanish
        'notfound.title': '404',
        'notfound.subtitle': '¡Ups! Página no encontrada',
        'notfound.home': 'Volver al Inicio',
        
        // Auth Page Spanish
        'auth.welcome.title': '¡Bienvenido de Vuelta!',
        'auth.welcome.subtitle': '¡Desbloquea tus superpoderes profesionales!',
        'auth.quote': '"La única manera de hacer un gran trabajo es amar lo que haces."',
        'auth.login': 'Iniciar Sesión',
        'auth.register': 'Registrarse',
        'auth.or': 'O',
        
        // Auth Components Spanish
        'auth.login.email': 'Correo Electrónico',
        'auth.login.password': 'Contraseña',
        'auth.login.success': '¡Inicio de sesión exitoso! Redirigiendo...',
        'auth.login.failed': 'Error en el inicio de sesión: ',
        'auth.login.processing': 'Procesando...',
        'auth.login.button': 'Iniciar Sesión',
        'auth.register.name': 'Nombre Completo',
        'auth.register.email': 'Correo Electrónico',
        'auth.register.password': 'Contraseña',
        'auth.register.confirmPassword': 'Confirmar Contraseña',
        'auth.register.success': '¡Registro exitoso! Redirigiendo...',
        'auth.register.failed': 'Error en el registro: ',
        'auth.register.processing': 'Procesando...',
        'auth.register.button': 'Registrarse',
            'auth.google.button': 'Continuar con Google',
    'auth.apple.button': 'Continuar con Apple',
    
    // AI Quiz Page Spanish
    'aiquiz.title': 'Quiz de IA',
    'aiquiz.subtitle': 'Prueba tu conocimiento con preguntas impulsadas por IA',
    'aiquiz.features.ai.title': 'Preguntas Impulsadas por IA',
    'aiquiz.features.ai.desc': 'Preguntas inteligentes adaptadas a tu empresa objetivo y rol',
    'aiquiz.features.company.title': 'Enfoque Específico de Empresa',
    'aiquiz.features.company.desc': 'Preguntas basadas en patrones reales de entrevista y requisitos',
    'aiquiz.features.explanations.title': 'Explicaciones Detalladas',
    'aiquiz.features.explanations.desc': 'Aprende de cada pregunta con explicaciones completas',
    'aiquiz.features.feedback.title': 'Retroalimentación Instantánea',
    'aiquiz.features.feedback.desc': 'Obtén resultados inmediatos y perspectivas de rendimiento',
    'aiquiz.form.company': 'Empresa',
    'aiquiz.form.role': 'Rol',
    'aiquiz.form.domain': 'Dominio',
    'aiquiz.form.difficulty': 'Dificultad',
    'aiquiz.form.start': 'Iniciar Quiz',
    'aiquiz.form.custom': 'Personalizado',
    'aiquiz.quiz.question': 'Pregunta',
    'aiquiz.quiz.of': 'de',
    'aiquiz.quiz.submit': 'Enviar Respuesta',
    'aiquiz.quiz.next': 'Siguiente Pregunta',
    'aiquiz.quiz.finish': 'Finalizar Quiz',
    'aiquiz.results.title': 'Resultados del Quiz',
    'aiquiz.results.score': 'Tu Puntuación',
    'aiquiz.results.correct': 'Respuestas Correctas',
    'aiquiz.results.incorrect': 'Respuestas Incorrectas',
    'aiquiz.results.time': 'Tiempo Empleado',
    'aiquiz.results.retake': 'Repetir Quiz',
    'aiquiz.results.new': 'Nuevo Quiz',
    'aiquiz.history.title': 'Historial de Quiz',
    'aiquiz.history.no': 'Aún no hay historial de quiz',
    'aiquiz.history.start': 'Inicia tu primer quiz para ver tu progreso',
    
    // Roadmap Generator Page Spanish
    'roadmap.title': 'Generador de Hojas de Ruta de Aprendizaje',
    'roadmap.subtitle': 'Crea caminos de aprendizaje personalizados para tus empresas objetivo',
    'roadmap.form.title': 'Generar Nueva Hoja de Ruta',
    'roadmap.form.company': 'Empresa',
    'roadmap.form.company.placeholder': 'ej., Google, Amazon, Microsoft',
    'roadmap.form.role': 'Rol',
    'roadmap.form.role.placeholder': 'ej., Ingeniero de Software, Científico de Datos',
    'roadmap.form.experience': 'Nivel de Experiencia',
    'roadmap.form.experience.beginner': 'Principiante (0-2 años)',
    'roadmap.form.experience.intermediate': 'Intermedio (2-5 años)',
    'roadmap.form.experience.advanced': 'Avanzado (5+ años)',
    'roadmap.form.goals': 'Objetivos Profesionales',
    'roadmap.form.goals.placeholder': 'Describe tus objetivos profesionales',
    'roadmap.form.timeline': 'Cronograma',
    'roadmap.form.timeline.placeholder': 'ej., 3 meses, 6 meses',
    'roadmap.form.generate': 'Generar Hoja de Ruta',
    'roadmap.display.title': 'Tu Hoja de Ruta de Aprendizaje',
    'roadmap.display.phase': 'Fase',
    'roadmap.display.weeks': 'semanas',
    'roadmap.display.skills': 'Habilidades para Aprender',
    'roadmap.display.resources': 'Recursos de Aprendizaje',
    'roadmap.display.projects': 'Proyectos de Práctica',
    'roadmap.display.milestones': 'Hitos',
    'roadmap.actions.save': 'Guardar Hoja de Ruta',
    'roadmap.actions.share': 'Compartir',
    'roadmap.actions.download': 'Descargar PDF',
    'roadmap.actions.new': 'Crear Nueva',
    
    // Email Generator Page Spanish
    'email.title': 'Generador de Emails con IA',
    'email.subtitle': 'Crea emails fríos profesionales y personalizados',
    'email.form.title': 'Crear Nuevo Email',
    'email.form.recipient': 'Destinatario',
    'email.form.recipient.placeholder': 'Nombre del destinatario o empresa',
    'email.form.company': 'Empresa',
    'email.form.company.placeholder': 'Nombre de la empresa objetivo',
    'email.form.role': 'Rol Solicitado',
    'email.form.role.placeholder': 'Título del trabajo al que aplicas',
    'email.form.experience': 'Experiencia Relevante',
    'email.form.experience.placeholder': 'Describe tu experiencia relevante para el rol',
    'email.form.tone': 'Tono del Mensaje',
    'email.form.tone.formal': 'Formal',
    'email.form.tone.friendly': 'Amigable',
    'email.form.tone.professional': 'Profesional',
    'email.form.generate': 'Generar Email',
    'email.display.title': 'Email Generado',
    'email.actions.copy': 'Copiar',
    'email.actions.download': 'Descargar',
    'email.actions.new': 'Crear Otro',
    
    // Interview Preps Page Spanish
    'interview.title': 'Preparación para Entrevistas',
    'interview.subtitle': 'Prepárate para entrevistas con recursos completos y práctica',
    'interview.sections.technical': 'Preparación Técnica',
    'interview.sections.behavioral': 'Preguntas de Comportamiento',
    'interview.sections.coding': 'Desafíos de Programación',
    'interview.sections.system': 'Diseño de Sistema',
    'interview.resources.title': 'Recursos de Preparación',
    'interview.resources.books': 'Libros Recomendados',
    'interview.resources.courses': 'Cursos de Entrenamiento',
    'interview.resources.practice': 'Sitios de Práctica',
    'interview.tips.title': 'Consejos para Entrevistas',
    'interview.tips.technical': 'Revisa conceptos fundamentales',
    'interview.tips.behavioral': 'Prepara historias STAR',
    'interview.tips.coding': 'Practica resolución de problemas',
    'interview.tips.system': 'Estudia patrones de diseño',
    
    // DSA Sheet Page Spanish
    'dsa.title': 'Hoja DSA',
    'dsa.subtitle': 'Lista completa de problemas de estructuras de datos y algoritmos',
    'dsa.categories.arrays': 'Arrays',
    'dsa.categories.strings': 'Strings',
    'dsa.categories.linkedlists': 'Listas Enlazadas',
    'dsa.categories.trees': 'Árboles',
    'dsa.categories.graphs': 'Grafos',
    'dsa.categories.dynamic': 'Programación Dinámica',
    'dsa.categories.greedy': 'Algoritmos Voraces',
    'dsa.difficulty.easy': 'Fácil',
    'dsa.difficulty.medium': 'Medio',
    'dsa.difficulty.hard': 'Difícil',
    'dsa.actions.solve': 'Resolver',
    'dsa.actions.practice': 'Practicar',
    'dsa.actions.review': 'Revisar',
    
    // Company Insights Page Spanish
    'company.title': 'Perspectivas de la Empresa',
    'company.subtitle': 'Descubre la cultura, tecnologías y requisitos de la empresa',
    'company.search.placeholder': 'Buscar empresa...',
    'company.overview.title': 'Descripción General',
    'company.overview.description': 'Descripción de la empresa y cultura',
    'company.tech.title': 'Tecnologías Utilizadas',
    'company.tech.frontend': 'Frontend',
    'company.tech.backend': 'Backend',
    'company.tech.database': 'Base de Datos',
    'company.tech.infrastructure': 'Infraestructura',
    'company.culture.title': 'Cultura de la Empresa',
    'company.culture.values': 'Valores',
    'company.culture.workstyle': 'Estilo de Trabajo',
    'company.culture.benefits': 'Beneficios',
    'company.interview.title': 'Proceso de Entrevista',
    'company.interview.process': 'Pasos',
    'company.interview.questions': 'Preguntas Comunes',
    'company.interview.tips': 'Consejos',
  },
  
  fr: {
    // Common
    'app.name': 'Drapels',
    'app.tagline': 'Plateforme d\'Insights',
    
    // Navigation
    'nav.home': 'Accueil',
    'nav.roadmaps': 'Feuilles de Route',
    'nav.companies': 'Entreprises',
    'nav.tools': 'Outils',
    'nav.more': 'Plus',
    'nav.login': 'Connexion',
    'nav.about': 'À Propos',
    'nav.contact': 'Contact',
    'nav.settings': 'Paramètres',
    
    // Tools dropdown
    'tools.aiquiz': 'Quiz IA',
    'tools.interviewprep': 'Préparation d\'Entretien',
    'tools.emailgenerator': 'Générateur d\'Email',
    'tools.dsasheet': 'Feuille DSA',
    
    // Profile
    'profile.greeting': 'Bonjour',
    'profile.profile': 'Profil',
    'profile.settings': 'Paramètres',
    'profile.logout': 'Déconnexion',
    
    // Settings page
    'settings.title': 'Paramètres',
    'settings.language': 'Langue',
    'settings.language.description': 'Sélectionnez votre langue préférée',
    'settings.profile': 'Profil',
    'settings.profile.description': 'Gérez vos informations de profil',
    'settings.account': 'Compte',
    'settings.account.description': 'Gérez les paramètres de votre compte',
    'settings.appearance': 'Apparence',
    'settings.appearance.description': 'Personnalisez l\'apparence de l\'application',
    'settings.privacy': 'Confidentialité et Conditions',
    'settings.privacy.description': 'Consultez notre politique de confidentialité et nos conditions de service',
    'settings.save': 'Enregistrer les Modifications',
    'settings.cancel': 'Annuler',
    'settings.darkmode': 'Mode Sombre',
    'settings.name': 'Nom',
    'settings.email': 'Email',
    'settings.photo': 'Photo de Profil',
    'settings.photo.change': 'Changer la Photo',
    'settings.photo.remove': 'Supprimer la Photo',
    'settings.photo.upload': 'Télécharger une Photo',
    'settings.progress': 'Votre Progression',
    'settings.progress.description': 'Suivez votre progrès d\'apprentissage',
    
    // Footer
    'footer.rights': 'Tous droits réservés',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': 'Conditions d\'Utilisation',
    'footer.contact': 'Contactez-nous',
    
    // Home page additional translations
    'home.testimonials.title': 'Ce que disent nos utilisateurs',
    'home.testimonials.subtitle': 'Histoires de réussite de notre communauté',
    'home.testimonials.priya.name': 'Priya Sharma',
    'home.testimonials.priya.role': 'SDE-1 chez Amazon',
    'home.testimonials.priya.content': 'Drapels m\'a aidé à structurer ma préparation et à décrocher mon emploi de rêve chez Amazon. Les feuilles de route spécifiques à l\'entreprise ont été révolutionnaires !',
    'home.testimonials.rahul.name': 'Rahul Kumar',
    'home.testimonials.rahul.role': 'Développeur Frontend chez Flipkart',
    'home.testimonials.rahul.content': 'Le générateur d\'emails froids m\'a aidé à me connecter avec les recruteurs. J\'ai reçu 3 appels d\'entretien en seulement 2 semaines !',
    'home.testimonials.ananya.name': 'Ananya Gupta',
    'home.testimonials.ananya.role': 'Développeur Backend chez Atlassian',
    'home.testimonials.ananya.content': 'Les perspectives complètes sur la culture d\'entreprise et la pile technologique m\'ont aidé à mieux me préparer aux entretiens.',
    'home.interactive.realtime.title': 'Rétroaction en Temps Réel',
    'home.interactive.realtime.desc': 'Obtenez une rétroaction instantanée sur votre progrès et vos performances pendant que vous travaillez à travers nos exercices et défis interactifs.',
    
    // About Page
    'about.title': 'À Propos de Drapels',
    'about.subtitle': 'Une initiative de startup dédiée à aider les étudiants à naviguer leurs parcours professionnels et à décrocher leurs emplois de rêve.',
    'about.mission.title': 'Notre Mission',
    'about.mission.para1': 'Chez Drapels, nous croyons que chaque étudiant mérite d\'avoir accès à des voies claires et structurées vers ses carrières de rêve. Notre plateforme connecte la brecha entre l\'apprentissage académique et les exigences de l\'industrie en fournissant des feuilles de route spécifiques aux entreprises, des ressources organisées et des perspectives internes.',
    'about.mission.para2': 'Fondée en 2025, Drapels est une initiative de startup par Arihant Jain, Taizun Kaptan et Aditya, qui ont vécu de première main les défis de naviguer les parcours professionnels de l\'industrie technologique. Notre mission est de démocratiser l\'accès aux ressources de préparation de carrière et de rendre le voyage de l\'étudiant au professionnel plus transparent et réalisable.',
    'about.founders.title': 'Rencontrez Nos Fondateurs',
    'about.founders.arihant.name': 'Arihant Jain',
    'about.founders.arihant.role': 'Constructeur Web | Cuisinier de Startup',
    'about.founders.arihant.bio': 'Pixels, bugs, café et chaos — je livre la perfection quotidiennement.',
    'about.founders.taizun.name': 'Taizun Kaptan',
    'about.founders.taizun.role': 'Développeur IA',
    'about.founders.taizun.bio': 'Enseigner aux machines à penser, pour que je n\'aie pas à le faire',
    'about.founders.aditya.name': 'Aditya Rajpoot',
    'about.founders.aditya.role': 'Développeur Frontend et Stratège Marketing',
    'about.founders.aditya.bio': 'Chez Drapels, j\'ai transformé les idées en interfaces, et la vision en visibilité',
    'about.join.title': 'Rejoignez Notre Mission',
    'about.join.desc': 'Que vous soyez un étudiant cherchant à lancer votre carrière ou un professionnel de l\'industrie intéressé par le mentorat, nous vous invitons à rejoindre notre communauté et à faire partie de notre voyage pour transformer la préparation de carrière.',

    // Contact Page French
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Vous avez des questions sur notre plateforme ? Vous voulez collaborer ? Nous aimerions avoir de vos nouvelles.',
    'contact.form.title': 'Envoyez-nous un Message',
    'contact.form.subtitle': 'Remplissez le formulaire ci-dessous et nous vous répondrons dès que possible.',
    'contact.form.firstName': 'Prénom',
    'contact.form.firstName.placeholder': 'Jean',
    'contact.form.lastName': 'Nom de Famille',
    'contact.form.lastName.placeholder': 'Dupont',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'jean@exemple.com',
    'contact.form.subject': 'Sujet',
    'contact.form.subject.placeholder': 'Comment pouvons-nous vous aider ?',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Dites-nous plus sur votre demande...',
    'contact.form.submit': 'Envoyer le Message',
    'contact.info.title': 'Informations de Contact',
    'contact.info.subtitle': 'Contactez-nous par l\'un de ces canaux.',
    'contact.info.email': 'Email',
    'contact.info.email.value': 'support@drapels.com',
    'contact.info.phone': 'Téléphone',
    'contact.info.phone.value': '+91 99999 99999',
    'contact.info.address': 'Adresse',
    'contact.info.address.value': 'Indore, MP',
    'contact.faq.title': 'Questions Fréquemment Posées',
    'contact.faq.started.question': 'Comment commencer ?',
    'contact.faq.started.answer': 'Inscrivez-vous pour un compte et explorez nos feuilles de route pour commencer votre voyage d\'apprentissage.',
    'contact.faq.free.question': 'La plateforme est-elle gratuite ?',
    'contact.faq.free.answer': 'Nous offrons des fonctionnalités gratuites et premium. Consultez nos tarifs pour plus de détails.',
    'contact.faq.contribute.question': 'Puis-je contribuer du contenu ?',
    'contact.faq.contribute.answer': 'Oui ! Nous accueillons les contributions de la communauté. Contactez-nous pour en savoir plus.',
    
    // NotFound Page French
    'notfound.title': '404',
    'notfound.subtitle': 'Oups ! Page non trouvée',
    'notfound.home': 'Retour à l\'Accueil',
    
    // Auth Page French
    'auth.welcome.title': 'Bon Retour !',
    'auth.welcome.subtitle': 'Débloquez vos superpouvoirs professionnels !',
    'auth.quote': '"La seule façon de faire un excellent travail est d\'aimer ce que vous faites."',
    'auth.login': 'Connexion',
    'auth.register': 'S\'inscrire',
    'auth.or': 'OU',
    
    // Auth Components French
    'auth.login.email': 'Email',
    'auth.login.password': 'Mot de passe',
    'auth.login.success': 'Connexion réussie ! Redirection...',
    'auth.login.failed': 'Échec de la connexion : ',
    'auth.login.processing': 'Traitement...',
    'auth.login.button': 'Se connecter',
    'auth.register.name': 'Nom complet',
    'auth.register.email': 'Email',
    'auth.register.password': 'Mot de passe',
    'auth.register.confirmPassword': 'Confirmer le mot de passe',
    'auth.register.success': 'Inscription réussie ! Redirection...',
    'auth.register.failed': 'Échec de l\'inscription : ',
    'auth.register.processing': 'Traitement...',
    'auth.register.button': 'S\'inscrire',
    'auth.google.button': 'Continuer avec Google',
    'auth.apple.button': 'Continuer avec Apple',
    
    // AI Quiz Page French
    'aiquiz.title': 'Quiz IA',
    'aiquiz.subtitle': 'Testez vos connaissances avec des questions alimentées par l\'IA',
    'aiquiz.features.ai.title': 'Questions Alimentées par l\'IA',
    'aiquiz.features.ai.desc': 'Questions intelligentes adaptées à votre entreprise cible et votre rôle',
    'aiquiz.features.company.title': 'Focus Spécifique à l\'Entreprise',
    'aiquiz.features.company.desc': 'Questions basées sur de vrais modèles d\'entretien et exigences',
    'aiquiz.features.explanations.title': 'Explications Détaillées',
    'aiquiz.features.explanations.desc': 'Apprenez de chaque question avec des explications complètes',
    'aiquiz.features.feedback.title': 'Rétroaction Instantanée',
    'aiquiz.features.feedback.desc': 'Obtenez des résultats immédiats et des perspectives de performance',
    'aiquiz.form.company': 'Entreprise',
    'aiquiz.form.role': 'Rôle',
    'aiquiz.form.domain': 'Domaine',
    'aiquiz.form.difficulty': 'Difficulté',
    'aiquiz.form.start': 'Commencer le Quiz',
    'aiquiz.form.custom': 'Personnalisé',
    'aiquiz.quiz.question': 'Question',
    'aiquiz.quiz.of': 'sur',
    'aiquiz.quiz.submit': 'Soumettre la Réponse',
    'aiquiz.quiz.next': 'Question Suivante',
    'aiquiz.quiz.finish': 'Terminer le Quiz',
    'aiquiz.results.title': 'Résultats du Quiz',
    'aiquiz.results.score': 'Votre Score',
    'aiquiz.results.correct': 'Réponses Correctes',
    'aiquiz.results.incorrect': 'Réponses Incorrectes',
    'aiquiz.results.time': 'Temps Passé',
    'aiquiz.results.retake': 'Refaire le Quiz',
    'aiquiz.results.new': 'Nouveau Quiz',
    'aiquiz.history.title': 'Historique des Quiz',
    'aiquiz.history.no': 'Aucun historique de quiz encore',
    'aiquiz.history.start': 'Commencez votre premier quiz pour voir vos progrès',
    
    // Roadmap Generator Page French
    'roadmap.title': 'Générateur de Feuilles de Route d\'Apprentissage',
    'roadmap.subtitle': 'Créez des parcours d\'apprentissage personnalisés pour vos entreprises cibles',
    'roadmap.form.title': 'Générer une Nouvelle Feuille de Route',
    'roadmap.form.company': 'Entreprise',
    'roadmap.form.company.placeholder': 'ex., Google, Amazon, Microsoft',
    'roadmap.form.role': 'Rôle',
    'roadmap.form.role.placeholder': 'ex., Ingénieur Logiciel, Scientifique des Données',
    'roadmap.form.experience': 'Niveau d\'Expérience',
    'roadmap.form.experience.beginner': 'Débutant (0-2 ans)',
    'roadmap.form.experience.intermediate': 'Intermédiaire (2-5 ans)',
    'roadmap.form.experience.advanced': 'Avancé (5+ ans)',
    'roadmap.form.goals': 'Objectifs Professionnels',
    'roadmap.form.goals.placeholder': 'Décrivez vos objectifs professionnels',
    'roadmap.form.timeline': 'Calendrier',
    'roadmap.form.timeline.placeholder': 'ex., 3 mois, 6 mois',
    'roadmap.form.generate': 'Générer la Feuille de Route',
    'roadmap.display.title': 'Votre Feuille de Route d\'Apprentissage',
    'roadmap.display.phase': 'Phase',
    'roadmap.display.weeks': 'semaines',
    'roadmap.display.skills': 'Compétences à Apprendre',
    'roadmap.display.resources': 'Ressources d\'Apprentissage',
    'roadmap.display.projects': 'Projets de Pratique',
    'roadmap.display.milestones': 'Jalons',
    'roadmap.actions.save': 'Sauvegarder la Feuille de Route',
    'roadmap.actions.share': 'Partager',
    'roadmap.actions.download': 'Télécharger PDF',
    'roadmap.actions.new': 'Créer une Nouvelle',
    
    // Email Generator Page French
    'email.title': 'Générateur d\'Emails IA',
    'email.subtitle': 'Créez des emails froids professionnels et personnalisés',
    'email.form.title': 'Créer un Nouvel Email',
    'email.form.recipient': 'Destinataire',
    'email.form.recipient.placeholder': 'Nom du destinataire ou entreprise',
    'email.form.company': 'Entreprise',
    'email.form.company.placeholder': 'Nom de l\'entreprise cible',
    'email.form.role': 'Rôle Sollicité',
    'email.form.role.placeholder': 'Titre du poste pour lequel vous postulez',
    'email.form.experience': 'Expérience Pertinente',
    'email.form.experience.placeholder': 'Décrivez votre expérience pertinente pour le rôle',
    'email.form.tone': 'Ton du Message',
    'email.form.tone.formal': 'Formel',
    'email.form.tone.friendly': 'Amical',
    'email.form.tone.professional': 'Professionnel',
    'email.form.generate': 'Générer l\'Email',
    'email.display.title': 'Email Généré',
    'email.actions.copy': 'Copier',
    'email.actions.download': 'Télécharger',
    'email.actions.new': 'Créer un Autre',
    
    // Interview Preps Page French
    'interview.title': 'Préparation aux Entretiens',
    'interview.subtitle': 'Préparez-vous aux entretiens avec des ressources complètes et de la pratique',
    'interview.sections.technical': 'Préparation Technique',
    'interview.sections.behavioral': 'Questions Comportementales',
    'interview.sections.coding': 'Défis de Programmation',
    'interview.sections.system': 'Conception de Système',
    'interview.resources.title': 'Ressources de Préparation',
    'interview.resources.books': 'Livres Recommandés',
    'interview.resources.courses': 'Cours de Formation',
    'interview.resources.practice': 'Sites de Pratique',
    'interview.tips.title': 'Conseils d\'Entretien',
    'interview.tips.technical': 'Révisez les concepts fondamentaux',
    'interview.tips.behavioral': 'Préparez des histoires STAR',
    'interview.tips.coding': 'Pratiquez la résolution de problèmes',
    'interview.tips.system': 'Étudiez les modèles de conception',
    
    // DSA Sheet Page French
    'dsa.title': 'Feuille DSA',
    'dsa.subtitle': 'Liste complète de problèmes de structures de données et d\'algorithmes',
    'dsa.categories.arrays': 'Tableaux',
    'dsa.categories.strings': 'Chaînes',
    'dsa.categories.linkedlists': 'Listes Chaînées',
    'dsa.categories.trees': 'Arbres',
    'dsa.categories.graphs': 'Graphes',
    'dsa.categories.dynamic': 'Programmation Dynamique',
    'dsa.categories.greedy': 'Algorithmes Gourmands',
    'dsa.difficulty.easy': 'Facile',
    'dsa.difficulty.medium': 'Moyen',
    'dsa.difficulty.hard': 'Difficile',
    'dsa.actions.solve': 'Résoudre',
    'dsa.actions.practice': 'Pratiquer',
    'dsa.actions.review': 'Réviser',
    
    // Company Insights Page French
    'company.title': 'Aperçus de l\'Entreprise',
    'company.subtitle': 'Découvrez la culture, les technologies et les exigences de l\'entreprise',
    'company.search.placeholder': 'Rechercher une entreprise...',
    'company.overview.title': 'Aperçu',
    'company.overview.description': 'Description de l\'entreprise et de la culture',
    'company.tech.title': 'Technologies Utilisées',
    'company.tech.frontend': 'Frontend',
    'company.tech.backend': 'Backend',
    'company.tech.database': 'Base de Données',
    'company.tech.infrastructure': 'Infrastructure',
    'company.culture.title': 'Culture d\'Entreprise',
    'company.culture.values': 'Valeurs',
    'company.culture.workstyle': 'Style de Travail',
    'company.culture.benefits': 'Avantages',
    'company.interview.title': 'Processus d\'Entretien',
    'company.interview.process': 'Étapes',
    'company.interview.questions': 'Questions Courantes',
    'company.interview.tips': 'Conseils',
  },
  };

// Create the provider component
interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  // Get initial language from localStorage or default to English
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage) {
        setLanguage(savedLanguage as Language);
    }
  }, []);

  // Update localStorage when language changes
  useEffect(() => {
    localStorage.setItem('language', language);
    // Update HTML lang attribute for accessibility
    document.documentElement.lang = language;
  }, [language]);

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook to use the language context
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};